
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-07T10:38:44-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "84df4392eee0315421ccda6ea4f068bfd6a396ce",
 "version": "2.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
