
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-08T15:34:46+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "0c4206de759b857a5260e61344ce1ab84ee540ed",
 "version": "0.4.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
