# coding: utf-8

"""
    Cachet Status Page API

    A java-friendly swagger documentation file based on the documentation for the Cachet Status Page https://cachethq.io/  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from cachethq_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_incident_update_by_id(self, incident, update, **kwargs):  # noqa: E501
        """Get an incident update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_incident_update_by_id(incident, update, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int incident: Unique incident id (required)
        :param int update: Unique incident update id (required)
        :return: SingleIncidentUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_incident_update_by_id_with_http_info(incident, update, **kwargs)  # noqa: E501
        else:
            (data) = self.get_incident_update_by_id_with_http_info(incident, update, **kwargs)  # noqa: E501
            return data

    def get_incident_update_by_id_with_http_info(self, incident, update, **kwargs):  # noqa: E501
        """Get an incident update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_incident_update_by_id_with_http_info(incident, update, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int incident: Unique incident id (required)
        :param int update: Unique incident update id (required)
        :return: SingleIncidentUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['incident', 'update']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_incident_update_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'incident' is set
        if ('incident' not in params or
                params['incident'] is None):
            raise ValueError("Missing the required parameter `incident` when calling `get_incident_update_by_id`")  # noqa: E501
        # verify the required parameter 'update' is set
        if ('update' not in params or
                params['update'] is None):
            raise ValueError("Missing the required parameter `update` when calling `get_incident_update_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'incident' in params:
            path_params['incident'] = params['incident']  # noqa: E501
        if 'update' in params:
            path_params['update'] = params['update']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/incidents/{incident}/updates/{update}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SingleIncidentUpdateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
