# Autogenerated file, do not edit!
# code fingerprint:
# 2.2.0+cpu_211813b_8ac9b20d4b090c213799e81acf48a55ea8d437d6_Release

__version__ = "2.2.0+cpu"
__ipex_gitrev__ = "211813b"
__torch_gitrev__ = ""
__gpu_onednn_gitrev__ = ""
__cpu_ideep_gitrev__ = "6d54ccdf83c0515240af8956a2de9404a3e86009"
__build_type__ = "Release"
