from enum import Enum


class Config(Enum):
    APPLICATION_NAME = "APPLICATION_NAME"
    APPLICATION_VERSION = "APPLICATION_VERSION"
    APPLICATION_DESCRIPTION = "APPLICATION_DESCRIPTION"
    APPLICATION_ROOT = "APPLICATION_ROOT"
    LOG_LEVEL = "LOG_LEVEL"
    LOG_RESPONSE_BODY = "LOG_RESPONSE_BODY"
    LOG_REQUEST_BODY = "LOG_REQUEST_BODY"
    DEBUG = "DEBUG"
    NUM_THREADS = "NUM_THREADS"
    URL_REPOSITORY = "URL_REPOSITORY"
    URL_BFF = "URL_BFF"
    STI_COOKIE = "STI_COOKIE"
    PORT = "PORT"
    API_TOKEN = "API_TOKEN"
    GITHUB_USER = "GITHUB_USER"
    GITHUB_PASS = "GITHUB_PASS"
