VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('06')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('51')
MAJOR_VERSION = 0
MINOR_VERSION = 0
PATCH_VERSION = 202402060551
version_date = '2024/02/06 05:51'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
