# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.angazovana_osoba_rcns import AngazovanaOsobaRcns

class TestAngazovanaOsobaRcns(unittest.TestCase):
    """AngazovanaOsobaRcns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AngazovanaOsobaRcns:
        """Test AngazovanaOsobaRcns
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AngazovanaOsobaRcns`
        """
        model = AngazovanaOsobaRcns()
        if include_optional:
            return AngazovanaOsobaRcns(
                jmeno = '',
                prijmeni = '',
                titul_pred_jmenem = '',
                titul_za_jmenem = '',
                datum_narozeni = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                platnost_od = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                platnost_do = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                nazev_angazma = '',
                poznamka = '',
                typ_angazma = '0',
                nazev_organu = '',
                kod_statu = '012',
                pravni_forma = '048012'
            )
        else:
            return AngazovanaOsobaRcns(
        )
        """

    def testAngazovanaOsobaRcns(self):
        """Test AngazovanaOsobaRcns"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
