# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.podil_vr import PodilVr

class TestPodilVr(unittest.TestCase):
    """PodilVr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PodilVr:
        """Test PodilVr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PodilVr`
        """
        model = PodilVr()
        if include_optional:
            return PodilVr(
                datum_zapisu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_vymazu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                text = '',
                vklad = openapi_client.models.obnos_vr.ObnosVr(
                    typ_obnos = '', 
                    hodnota = '', ),
                velikost_podilu = openapi_client.models.obnos_vr.ObnosVr(
                    typ_obnos = '', 
                    hodnota = '', ),
                splaceni = openapi_client.models.obnos_vr.ObnosVr(
                    typ_obnos = '', 
                    hodnota = '', ),
                zastavni_pravo = [
                    openapi_client.models.zastavni_pravo_vr.ZastavniPravoVr()
                    ]
            )
        else:
            return PodilVr(
        )
        """

    def testPodilVr(self):
        """Test PodilVr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
