# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ciselnik import Ciselnik

class TestCiselnik(unittest.TestCase):
    """Ciselnik unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ciselnik:
        """Test Ciselnik
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ciselnik`
        """
        model = Ciselnik()
        if include_optional:
            return Ciselnik(
                kod_ciselniku = '0',
                nazev_ciselniku = '',
                polozky_ciselniku = [
                    openapi_client.models.polozka_ciselniku.PolozkaCiselniku(
                        kod = '0', 
                        nazev = [
                            openapi_client.models.nazev_polozky.NazevPolozky(
                                kod_jazyka = '', )
                            ], 
                        platnost_od = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        platnost_do = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        kod_nadrizeny = '0', )
                    ],
                zdroj_ciselniku = '0'
            )
        else:
            return Ciselnik(
        )
        """

    def testCiselnik(self):
        """Test Ciselnik"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
