# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.skola_zarizeni import SkolaZarizeni

class TestSkolaZarizeni(unittest.TestCase):
    """SkolaZarizeni unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkolaZarizeni:
        """Test SkolaZarizeni
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkolaZarizeni`
        """
        model = SkolaZarizeni()
        if include_optional:
            return SkolaZarizeni(
                kontakty = openapi_client.models.kontakty_rs.KontaktyRs(
                    telefon = '0', 
                    fax = '0', 
                    email = [
                        '0'
                        ], 
                    www = '0', ),
                izo = '0',
                obchodni_jmeno = '0',
                obchodni_jmeno_zkracene = '0',
                typ_skoly = '0',
                adresa = openapi_client.models.adresa.Adresa(
                    kod_statu = '012', 
                    nazev_statu = '', 
                    kod_kraje = 0, 
                    nazev_kraje = '', 
                    kod_okresu = 0, 
                    nazev_okresu = '', 
                    kod_obce = 0, 
                    nazev_obce = '', 
                    kod_spravniho_obvodu = 0, 
                    nazev_spravniho_obvodu = '', 
                    kod_mestskeho_obvodu = 0, 
                    nazev_mestskeho_obvodu = '', 
                    kod_mestske_casti_obvodu = 0, 
                    kod_ulice = 0, 
                    nazev_mestske_casti_obvodu = '', 
                    nazev_ulice = '', 
                    cislo_domovni = 56, 
                    doplnek_adresy = '', 
                    kod_casti_obce = 0, 
                    cislo_orientacni = 56, 
                    cislo_orientacni_pismeno = '', 
                    nazev_casti_obce = '', 
                    kod_adresniho_mista = 0, 
                    psc = 56, 
                    textova_adresa = '', 
                    cislo_do_adresy = '', 
                    typ_cislo_domovni = '0', 
                    standardizace_adresy = True, 
                    psc_txt = '', ),
                datum_vzniku = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_zaniku = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return SkolaZarizeni(
        )
        """

    def testSkolaZarizeni(self):
        """Test SkolaZarizeni"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
