# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.angazovana_osoba_szr_zaklad import AngazovanaOsobaSzrZaklad

class TestAngazovanaOsobaSzrZaklad(unittest.TestCase):
    """AngazovanaOsobaSzrZaklad unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AngazovanaOsobaSzrZaklad:
        """Test AngazovanaOsobaSzrZaklad
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AngazovanaOsobaSzrZaklad`
        """
        model = AngazovanaOsobaSzrZaklad()
        if include_optional:
            return AngazovanaOsobaSzrZaklad(
                jmeno = '',
                prijmeni = '',
                titul_pred_jmenem = '',
                titul_za_jmenem = '',
                datum_narozeni = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                typ_angazma = '0'
            )
        else:
            return AngazovanaOsobaSzrZaklad(
        )
        """

    def testAngazovanaOsobaSzrZaklad(self):
        """Test AngazovanaOsobaSzrZaklad"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
