# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.funkce_vr import FunkceVr

class TestFunkceVr(unittest.TestCase):
    """FunkceVr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunkceVr:
        """Test FunkceVr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunkceVr`
        """
        model = FunkceVr()
        if include_optional:
            return FunkceVr(
                vznik_funkce = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                zanik_funkce = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                nazev = ''
            )
        else:
            return FunkceVr(
        )
        """

    def testFunkceVr(self):
        """Test FunkceVr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
