# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.uvolneny_podil_vr import UvolnenyPodilVr

class TestUvolnenyPodilVr(unittest.TestCase):
    """UvolnenyPodilVr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UvolnenyPodilVr:
        """Test UvolnenyPodilVr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UvolnenyPodilVr`
        """
        model = UvolnenyPodilVr()
        if include_optional:
            return UvolnenyPodilVr(
                datum_zapisu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_vymazu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                clenstvi = openapi_client.models.angazma_clenstvi_vr.AngazmaClenstviVr(
                    text_za_osobu = '', 
                    clenstvi = openapi_client.models.clenstvi_vr.ClenstviVr(
                        vznik_clenstvi = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        zanik_clenstvi = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                    funkce = openapi_client.models.funkce_vr.FunkceVr(
                        vznik_funkce = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        zanik_funkce = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        nazev = '', ), 
                    text_zruseni = '', ),
                podil = openapi_client.models.podil_vr.PodilVr()
            )
        else:
            return UvolnenyPodilVr(
        )
        """

    def testUvolnenyPodilVr(self):
        """Test UvolnenyPodilVr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
