# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.stav_subjektu import StavSubjektu

class TestStavSubjektu(unittest.TestCase):
    """StavSubjektu unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StavSubjektu:
        """Test StavSubjektu
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StavSubjektu`
        """
        model = StavSubjektu()
        if include_optional:
            return StavSubjektu(
                popis = '',
                platnost_od = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                stav_subjektu = '0'
            )
        else:
            return StavSubjektu(
        )
        """

    def testStavSubjektu(self):
        """Test StavSubjektu"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
