# coding: utf-8

"""
    Curia Platform API

    These are the docs for the curia platform API. To test, generate an authorization token first.  # noqa: E501

    OpenAPI spec version: 3.11.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateTectonFeatureDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'feature_view_id': 'str',
        'feature_table_id': 'str',
        'metadata': 'object'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'feature_view_id': 'featureViewId',
        'feature_table_id': 'featureTableId',
        'metadata': 'metadata'
    }

    def __init__(self, name=None, description=None, feature_view_id=None, feature_table_id=None, metadata=None):  # noqa: E501
        """CreateTectonFeatureDto - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._feature_view_id = None
        self._feature_table_id = None
        self._metadata = None
        self.discriminator = None
        self.name = name
        if description is not None:
            self.description = description
        if feature_view_id is not None:
            self.feature_view_id = feature_view_id
        if feature_table_id is not None:
            self.feature_table_id = feature_table_id
        if metadata is not None:
            self.metadata = metadata

    @property
    def name(self):
        """Gets the name of this CreateTectonFeatureDto.  # noqa: E501


        :return: The name of this CreateTectonFeatureDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateTectonFeatureDto.


        :param name: The name of this CreateTectonFeatureDto.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this CreateTectonFeatureDto.  # noqa: E501


        :return: The description of this CreateTectonFeatureDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateTectonFeatureDto.


        :param description: The description of this CreateTectonFeatureDto.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def feature_view_id(self):
        """Gets the feature_view_id of this CreateTectonFeatureDto.  # noqa: E501


        :return: The feature_view_id of this CreateTectonFeatureDto.  # noqa: E501
        :rtype: str
        """
        return self._feature_view_id

    @feature_view_id.setter
    def feature_view_id(self, feature_view_id):
        """Sets the feature_view_id of this CreateTectonFeatureDto.


        :param feature_view_id: The feature_view_id of this CreateTectonFeatureDto.  # noqa: E501
        :type: str
        """

        self._feature_view_id = feature_view_id

    @property
    def feature_table_id(self):
        """Gets the feature_table_id of this CreateTectonFeatureDto.  # noqa: E501


        :return: The feature_table_id of this CreateTectonFeatureDto.  # noqa: E501
        :rtype: str
        """
        return self._feature_table_id

    @feature_table_id.setter
    def feature_table_id(self, feature_table_id):
        """Sets the feature_table_id of this CreateTectonFeatureDto.


        :param feature_table_id: The feature_table_id of this CreateTectonFeatureDto.  # noqa: E501
        :type: str
        """

        self._feature_table_id = feature_table_id

    @property
    def metadata(self):
        """Gets the metadata of this CreateTectonFeatureDto.  # noqa: E501


        :return: The metadata of this CreateTectonFeatureDto.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this CreateTectonFeatureDto.


        :param metadata: The metadata of this CreateTectonFeatureDto.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateTectonFeatureDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateTectonFeatureDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
