# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truera/protobuf/dataquality/schema_mismatch_records.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9truera/protobuf/dataquality/schema_mismatch_records.proto\x12\x12truera.dataquality\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n\x1bRowsetSchemaMismatchRecords\x12\x11\n\trowset_id\x18\x01 \x01(\t\x12\x17\n\x0ftotal_row_count\x18\x04 \x01(\x03\x12\x15\n\rfeature_names\x18\x02 \x03(\t\x12\x43\n\x14schema_mismatch_rows\x18\x03 \x03(\x0b\x32%.truera.dataquality.SchemaMismatchRow\"\xa7\x01\n\x11SchemaMismatchRow\x12\x31\n\rrow_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nrow_string\x18\x01 \x03(\t\x12%\n\x1dschema_mismatch_feature_index\x18\x02 \x03(\x05\x12$\n\x1cschema_mismatch_feature_name\x18\x03 \x03(\tBx\n\x1f\x63om.truera.protobuf.dataqualityB\x1aSchemaMismatchRecordsProtoP\x01Z7truera.com/protobuf/dataquality/schema_mismatch_recordsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truera.protobuf.dataquality.schema_mismatch_records_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.truera.protobuf.dataqualityB\032SchemaMismatchRecordsProtoP\001Z7truera.com/protobuf/dataquality/schema_mismatch_records'
  _ROWSETSCHEMAMISMATCHRECORDS._serialized_start=115
  _ROWSETSCHEMAMISMATCHRECORDS._serialized_end=280
  _SCHEMAMISMATCHROW._serialized_start=283
  _SCHEMAMISMATCHROW._serialized_end=450
# @@protoc_insertion_point(module_scope)
