# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class KodChybyEnum(str, Enum):
    """
    Chybové kódy.
    """

    """
    allowed enum values
    """
    OBECNA_CHYBA = 'OBECNA_CHYBA'
    CHYBA_VSTUPU = 'CHYBA_VSTUPU'
    NENALEZENO = 'NENALEZENO'
    NENI_IMPLEMENTOVANO = 'NENI_IMPLEMENTOVANO'
    NEPRIHLASENY_UZIVATEL = 'NEPRIHLASENY_UZIVATEL'
    NENI_OPRAVNENI = 'NENI_OPRAVNENI'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KodChybyEnum from a JSON string"""
        return cls(json.loads(json_str))


