
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-05T18:49:14+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "938238d65a4f8e0625f04a23d4050cc73f30cd77",
 "version": "0.4.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
