from enum import Enum

class megaBOOL(Enum):
    TRUE = 1
    FALSE = 0
    NEITHER = 2
    BOTH = 3
    MAYBE = 4
    TRUEISH = 5
    FALSEISH = 6
    DEPENDS = 7
    OSCILLATING = 8
    COMPLICATED = 9
    PARTIALLY_TRUE = 10
    MISLEADING = 11
    AMBIGUOUS = 12
    EXAGGERATED = 13
    OUTDATED = 14
    UNVERIFIED = 15
    SUBJECTIVE = 16
    HYPOTHETICAL = 17
    MISTAKEN = 18
    DEBATABLE = 19
    UNCERTAIN = 20
    DOUBTFUL = 21
    INCONCLUSIVE = 22
    CONTRADICTORY = 23
    PROBABLE = 24
    IMPROBABLE = 25
    PLAUSIBLE = 26
    UNLIKELY = 27
    CONFIRMED = 28
    VALID = 29
    INVALID = 30
    SPECULATIVE = 31
    ASSUMED = 32