# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WorkloadDetailed(BaseModel):
    """
    WorkloadDetailed
    """ # noqa: E501
    slug: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    org_slug: Optional[StrictStr] = None
    space_slug: Optional[StrictStr] = None
    instance_slug: Optional[StrictStr] = None
    session_id: Optional[StrictStr] = None
    creation_timestamp: Optional[StrictStr] = None
    shared: Optional[StrictStr] = None
    compute_units: Optional[StrictStr] = None
    addons_compute_units: Optional[StrictStr] = None
    gpu: Optional[StrictStr] = None
    current_cpu: Optional[StrictStr] = None
    current_memory: Optional[StrictStr] = None
    node_pool: Optional[StrictStr] = None
    max_cpu: Optional[StrictStr] = None
    max_memory: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["slug", "name", "status", "org_slug", "space_slug", "instance_slug", "session_id", "creation_timestamp", "shared", "compute_units", "addons_compute_units", "gpu", "current_cpu", "current_memory", "node_pool", "max_cpu", "max_memory"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkloadDetailed from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WorkloadDetailed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "slug": obj.get("slug"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "org_slug": obj.get("org_slug"),
            "space_slug": obj.get("space_slug"),
            "instance_slug": obj.get("instance_slug"),
            "session_id": obj.get("session_id"),
            "creation_timestamp": obj.get("creation_timestamp"),
            "shared": obj.get("shared"),
            "compute_units": obj.get("compute_units"),
            "addons_compute_units": obj.get("addons_compute_units"),
            "gpu": obj.get("gpu"),
            "current_cpu": obj.get("current_cpu"),
            "current_memory": obj.get("current_memory"),
            "node_pool": obj.get("node_pool"),
            "max_cpu": obj.get("max_cpu"),
            "max_memory": obj.get("max_memory")
        })
        return _obj


