
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-10T20:16:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd4e3857f90ae6e02f9c6efc7669af198807a807",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
