
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-09T13:37:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecaab1ac80a58bf60e30047cf46babc2b32bccb5",
 "version": "0.2.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
