from .addwidgets_ps import icons_path
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Vis_Tab.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QLabel,
    QLayout, QPushButton, QSizePolicy, QSlider,
    QSpacerItem, QStackedWidget, QToolButton, QVBoxLayout,
    QWidget)

from .addwidgets_ps import (CollapsibleBox, MplCanvas, MyQDoubleSpin, MyQSpin,
    MyTabLabel, MyToolButton)

class Ui_VisTab(object):
    def setupUi(self, VisTab):
        if not VisTab.objectName():
            VisTab.setObjectName(u"VisTab")
        VisTab.resize(500, 680)
        VisTab.setMinimumSize(QSize(480, 340))
        VisTab.setMaximumSize(QSize(1000, 16777215))
        VisTab.setFocusPolicy(Qt.ClickFocus)
        icon1 = QIcon()
        icon1.addFile(u""+ icons_path +"vect_field.png", QSize(), QIcon.Normal, QIcon.Off)
        VisTab.setWindowIcon(icon1)
        self.verticalLayout = QVBoxLayout(VisTab)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.w_Mode = QWidget(VisTab)
        self.w_Mode.setObjectName(u"w_Mode")
        self.w_Mode.setMinimumSize(QSize(0, 40))
        self.w_Mode.setMaximumSize(QSize(16777215, 40))
        font = QFont()
        font.setPointSize(11)
        self.w_Mode.setFont(font)
        self.horizontalLayout_8 = QHBoxLayout(self.w_Mode)
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 10)
        self.icon = QLabel(self.w_Mode)
        self.icon.setObjectName(u"icon")
        self.icon.setMinimumSize(QSize(35, 35))
        self.icon.setMaximumSize(QSize(35, 35))
        self.icon.setPixmap(QPixmap(u""+ icons_path +"vect_field.png"))
        self.icon.setScaledContents(True)

        self.horizontalLayout_8.addWidget(self.icon)

        self.name_tab = MyTabLabel(self.w_Mode)
        self.name_tab.setObjectName(u"name_tab")
        self.name_tab.setMinimumSize(QSize(200, 35))
        self.name_tab.setMaximumSize(QSize(16777215, 35))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.name_tab.setFont(font1)

        self.horizontalLayout_8.addWidget(self.name_tab)

        self.hs1 = QSpacerItem(70, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_8.addItem(self.hs1)

        self.label_number = QLabel(self.w_Mode)
        self.label_number.setObjectName(u"label_number")
        self.label_number.setMinimumSize(QSize(35, 0))
        font2 = QFont()
        font2.setPointSize(9)
        self.label_number.setFont(font2)
        self.label_number.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_8.addWidget(self.label_number)

        self.hs_2 = QSpacerItem(5, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_8.addItem(self.hs_2)

        self.button_back = QToolButton(self.w_Mode)
        self.button_back.setObjectName(u"button_back")
        self.button_back.setMinimumSize(QSize(24, 24))
        self.button_back.setMaximumSize(QSize(24, 24))
        icon2 = QIcon()
        icon2.addFile(u""+ icons_path +"undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_back.setIcon(icon2)
        self.button_back.setIconSize(QSize(20, 20))

        self.horizontalLayout_8.addWidget(self.button_back)

        self.button_forward = QToolButton(self.w_Mode)
        self.button_forward.setObjectName(u"button_forward")
        self.button_forward.setMinimumSize(QSize(24, 24))
        self.button_forward.setMaximumSize(QSize(24, 24))
        icon3 = QIcon()
        icon3.addFile(u""+ icons_path +"redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_forward.setIcon(icon3)
        self.button_forward.setIconSize(QSize(20, 20))

        self.horizontalLayout_8.addWidget(self.button_forward)

        self.w_button_close_tab = QWidget(self.w_Mode)
        self.w_button_close_tab.setObjectName(u"w_button_close_tab")
        self.w_button_close_tab.setMinimumSize(QSize(18, 24))
        self.w_button_close_tab.setMaximumSize(QSize(18, 24))
        self.horizontalLayout_4 = QHBoxLayout(self.w_button_close_tab)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.button_close_tab = QToolButton(self.w_button_close_tab)
        self.button_close_tab.setObjectName(u"button_close_tab")
        self.button_close_tab.setMinimumSize(QSize(18, 18))
        self.button_close_tab.setMaximumSize(QSize(18, 18))
        self.button_close_tab.setLayoutDirection(Qt.LeftToRight)
        self.button_close_tab.setStyleSheet(u"QToolButton{\n"
"border-radius: 15px;\n"
"}")
        icon4 = QIcon()
        icon4.addFile(u""+ icons_path +"close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_close_tab.setIcon(icon4)
        self.button_close_tab.setIconSize(QSize(15, 15))

        self.horizontalLayout_4.addWidget(self.button_close_tab)


        self.horizontalLayout_8.addWidget(self.w_button_close_tab)


        self.verticalLayout.addWidget(self.w_Mode)

        self.line = QFrame(VisTab)
        self.line.setObjectName(u"line")
        self.line.setMinimumSize(QSize(0, 5))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.verticalLayout.addWidget(self.line)

        self.w_plot = QWidget(VisTab)
        self.w_plot.setObjectName(u"w_plot")
        self.lay_w_Plot = QVBoxLayout(self.w_plot)
        self.lay_w_Plot.setSpacing(5)
        self.lay_w_Plot.setObjectName(u"lay_w_Plot")
        self.lay_w_Plot.setContentsMargins(0, 0, 0, 0)
        self.CollapBox_PlotTools = CollapsibleBox(self.w_plot)
        self.CollapBox_PlotTools.setObjectName(u"CollapBox_PlotTools")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CollapBox_PlotTools.sizePolicy().hasHeightForWidth())
        self.CollapBox_PlotTools.setSizePolicy(sizePolicy)
        self.CollapBox_PlotTools.setMinimumSize(QSize(0, 170))
        self.CollapBox_PlotTools.setMaximumSize(QSize(16777215, 170))
        self.verticalLayout_24 = QVBoxLayout(self.CollapBox_PlotTools)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.lay_CollapBox_PlotTools = QHBoxLayout()
        self.lay_CollapBox_PlotTools.setSpacing(0)
        self.lay_CollapBox_PlotTools.setObjectName(u"lay_CollapBox_PlotTools")
        self.lay_CollapBox_PlotTools.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.tool_CollapBox_PlotTools = QToolButton(self.CollapBox_PlotTools)
        self.tool_CollapBox_PlotTools.setObjectName(u"tool_CollapBox_PlotTools")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tool_CollapBox_PlotTools.sizePolicy().hasHeightForWidth())
        self.tool_CollapBox_PlotTools.setSizePolicy(sizePolicy1)
        self.tool_CollapBox_PlotTools.setMinimumSize(QSize(0, 20))
        self.tool_CollapBox_PlotTools.setMaximumSize(QSize(16777215, 20))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        self.tool_CollapBox_PlotTools.setFont(font3)
        self.tool_CollapBox_PlotTools.setFocusPolicy(Qt.ClickFocus)
        self.tool_CollapBox_PlotTools.setStyleSheet(u"QToolButton { border: none; }")
        self.tool_CollapBox_PlotTools.setCheckable(True)
        self.tool_CollapBox_PlotTools.setChecked(True)
        self.tool_CollapBox_PlotTools.setPopupMode(QToolButton.InstantPopup)
        self.tool_CollapBox_PlotTools.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        self.tool_CollapBox_PlotTools.setArrowType(Qt.DownArrow)

        self.lay_CollapBox_PlotTools.addWidget(self.tool_CollapBox_PlotTools)

        self.hsp_CollapBox_PlotTools = QSpacerItem(100, 20, QSizePolicy.Preferred, QSizePolicy.Minimum)

        self.lay_CollapBox_PlotTools.addItem(self.hsp_CollapBox_PlotTools)

        self.push_CollapBox_PlotTools = MyToolButton(self.CollapBox_PlotTools)
        self.push_CollapBox_PlotTools.setObjectName(u"push_CollapBox_PlotTools")
        self.push_CollapBox_PlotTools.setMinimumSize(QSize(18, 18))
        self.push_CollapBox_PlotTools.setMaximumSize(QSize(18, 18))
        self.push_CollapBox_PlotTools.setFocusPolicy(Qt.ClickFocus)
        self.push_CollapBox_PlotTools.setLayoutDirection(Qt.LeftToRight)
        self.push_CollapBox_PlotTools.setIcon(icon2)
        self.push_CollapBox_PlotTools.setIconSize(QSize(12, 12))

        self.lay_CollapBox_PlotTools.addWidget(self.push_CollapBox_PlotTools)


        self.verticalLayout_24.addLayout(self.lay_CollapBox_PlotTools)

        self.Plot_tools = QGroupBox(self.CollapBox_PlotTools)
        self.Plot_tools.setObjectName(u"Plot_tools")
        sizePolicy.setHeightForWidth(self.Plot_tools.sizePolicy().hasHeightForWidth())
        self.Plot_tools.setSizePolicy(sizePolicy)
        self.Plot_tools.setMinimumSize(QSize(0, 150))
        self.Plot_tools.setMaximumSize(QSize(16777215, 150))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setItalic(False)
        font4.setKerning(False)
        self.Plot_tools.setFont(font4)
        self.Plot_tools.setStyleSheet(u"QGroupBox{border: 1px solid gray; border-radius: 6px;}\n"
"")
        self.verticalLayout_2 = QVBoxLayout(self.Plot_tools)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.w_Plot_Contour_Map = QWidget(self.Plot_tools)
        self.w_Plot_Contour_Map.setObjectName(u"w_Plot_Contour_Map")
        self.w_Plot_Contour_Map.setMinimumSize(QSize(0, 140))
        self.w_Plot_Contour_Map.setMaximumSize(QSize(16777215, 140))
        self.horizontalLayout = QHBoxLayout(self.w_Plot_Contour_Map)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.w_Contour_Map = QWidget(self.w_Plot_Contour_Map)
        self.w_Contour_Map.setObjectName(u"w_Contour_Map")
        self.w_Contour_Map.setMinimumSize(QSize(220, 140))
        self.w_Contour_Map.setMaximumSize(QSize(16777215, 140))
        self.verticalLayout_11 = QVBoxLayout(self.w_Contour_Map)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.w_addButtons = QWidget(self.w_Contour_Map)
        self.w_addButtons.setObjectName(u"w_addButtons")
        self.w_addButtons.setMinimumSize(QSize(0, 25))
        self.w_addButtons.setMaximumSize(QSize(16777215, 25))
        self.horizontalLayout_2 = QHBoxLayout(self.w_addButtons)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.button_showIW = QPushButton(self.w_addButtons)
        self.button_showIW.setObjectName(u"button_showIW")
        self.button_showIW.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.button_showIW)

        self.button_showMTF = QPushButton(self.w_addButtons)
        self.button_showMTF.setObjectName(u"button_showMTF")
        self.button_showMTF.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.button_showMTF)

        self.button_subMIN = QPushButton(self.w_addButtons)
        self.button_subMIN.setObjectName(u"button_subMIN")
        self.button_subMIN.setCheckable(True)

        self.horizontalLayout_2.addWidget(self.button_subMIN)

        self.hs_addbuttons = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.hs_addbuttons)


        self.verticalLayout_11.addWidget(self.w_addButtons)

        self.vs_cmap_3 = QSpacerItem(20, 5, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_11.addItem(self.vs_cmap_3)

        self.label_map_var = QLabel(self.w_Contour_Map)
        self.label_map_var.setObjectName(u"label_map_var")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_map_var.sizePolicy().hasHeightForWidth())
        self.label_map_var.setSizePolicy(sizePolicy2)
        self.label_map_var.setMinimumSize(QSize(0, 20))
        self.label_map_var.setMaximumSize(QSize(16777215, 20))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setItalic(True)
        self.label_map_var.setFont(font5)

        self.verticalLayout_11.addWidget(self.label_map_var)

        self.combo_map_var = QComboBox(self.w_Contour_Map)
        self.combo_map_var.addItem("")
        self.combo_map_var.addItem("")
        self.combo_map_var.addItem("")
        self.combo_map_var.addItem("")
        self.combo_map_var.addItem("")
        self.combo_map_var.addItem("")
        self.combo_map_var.addItem("")
        self.combo_map_var.setObjectName(u"combo_map_var")
        self.combo_map_var.setMinimumSize(QSize(0, 24))
        self.combo_map_var.setMaximumSize(QSize(16777215, 24))
        self.combo_map_var.setFont(font)

        self.verticalLayout_11.addWidget(self.combo_map_var)

        self.vs_cmap_1 = QSpacerItem(20, 10, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_11.addItem(self.vs_cmap_1)

        self.label_field_rep = QLabel(self.w_Contour_Map)
        self.label_field_rep.setObjectName(u"label_field_rep")
        sizePolicy2.setHeightForWidth(self.label_field_rep.sizePolicy().hasHeightForWidth())
        self.label_field_rep.setSizePolicy(sizePolicy2)
        self.label_field_rep.setMinimumSize(QSize(0, 20))
        self.label_field_rep.setMaximumSize(QSize(16777215, 20))
        self.label_field_rep.setFont(font5)

        self.verticalLayout_11.addWidget(self.label_field_rep)

        self.combo_field_rep = QComboBox(self.w_Contour_Map)
        self.combo_field_rep.addItem("")
        self.combo_field_rep.addItem("")
        self.combo_field_rep.addItem("")
        self.combo_field_rep.setObjectName(u"combo_field_rep")
        self.combo_field_rep.setMinimumSize(QSize(0, 24))
        self.combo_field_rep.setMaximumSize(QSize(16777215, 24))
        self.combo_field_rep.setFont(font)

        self.verticalLayout_11.addWidget(self.combo_field_rep)

        self.vs_cmap_2 = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_11.addItem(self.vs_cmap_2)

        self.verticalLayout_11.setStretch(2, 1)
        self.verticalLayout_11.setStretch(3, 1)
        self.verticalLayout_11.setStretch(5, 1)
        self.verticalLayout_11.setStretch(6, 1)

        self.horizontalLayout.addWidget(self.w_Contour_Map)

        self.w_image_levels = QWidget(self.w_Plot_Contour_Map)
        self.w_image_levels.setObjectName(u"w_image_levels")
        self.w_image_levels.setMinimumSize(QSize(0, 140))
        self.w_image_levels.setMaximumSize(QSize(16777215, 140))
        self.verticalLayout_7 = QVBoxLayout(self.w_image_levels)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 5)
        self.image_levels_control = QWidget(self.w_image_levels)
        self.image_levels_control.setObjectName(u"image_levels_control")
        self.image_levels_control.setMinimumSize(QSize(0, 24))
        self.image_levels_control.setMaximumSize(QSize(16777215, 24))
        self.horizontalLayout_5 = QHBoxLayout(self.image_levels_control)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.button_restore = QToolButton(self.image_levels_control)
        self.button_restore.setObjectName(u"button_restore")
        self.button_restore.setMinimumSize(QSize(20, 20))
        self.button_restore.setMaximumSize(QSize(20, 20))
        icon5 = QIcon()
        icon5.addFile(u""+ icons_path +"reset.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_restore.setIcon(icon5)
        self.button_restore.setIconSize(QSize(12, 12))
        self.button_restore.setArrowType(Qt.NoArrow)

        self.horizontalLayout_5.addWidget(self.button_restore)

        self.button_resize = QToolButton(self.image_levels_control)
        self.button_resize.setObjectName(u"button_resize")
        self.button_resize.setMinimumSize(QSize(20, 20))
        self.button_resize.setMaximumSize(QSize(20, 20))
        icon6 = QIcon()
        icon6.addFile(u""+ icons_path +"resize_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_resize.setIcon(icon6)
        self.button_resize.setIconSize(QSize(13, 13))
        self.button_resize.setArrowType(Qt.NoArrow)

        self.horizontalLayout_5.addWidget(self.button_resize)

        self.button_invert_y = QToolButton(self.image_levels_control)
        self.button_invert_y.setObjectName(u"button_invert_y")
        self.button_invert_y.setMinimumSize(QSize(20, 20))
        self.button_invert_y.setMaximumSize(QSize(20, 20))
        icon7 = QIcon()
        icon7.addFile(u""+ icons_path +"flip_y.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_invert_y.setIcon(icon7)
        self.button_invert_y.setCheckable(True)
        self.button_invert_y.setArrowType(Qt.NoArrow)

        self.horizontalLayout_5.addWidget(self.button_invert_y)

        self.hs_lev_3 = QSpacerItem(85, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_5.addItem(self.hs_lev_3)

        self.label_title = QLabel(self.image_levels_control)
        self.label_title.setObjectName(u"label_title")
        sizePolicy2.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy2)
        self.label_title.setMinimumSize(QSize(0, 20))
        self.label_title.setMaximumSize(QSize(16777215, 20))
        self.label_title.setFont(font5)

        self.horizontalLayout_5.addWidget(self.label_title)

        self.w_arrows = QWidget(self.image_levels_control)
        self.w_arrows.setObjectName(u"w_arrows")
        self.w_arrows.setMinimumSize(QSize(0, 24))
        self.w_arrows.setMaximumSize(QSize(16777215, 24))
        self.horizontalLayout_3 = QHBoxLayout(self.w_arrows)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.left = QToolButton(self.w_arrows)
        self.left.setObjectName(u"left")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.left.sizePolicy().hasHeightForWidth())
        self.left.setSizePolicy(sizePolicy3)
        self.left.setMinimumSize(QSize(14, 14))
        self.left.setMaximumSize(QSize(14, 14))
        self.left.setIconSize(QSize(15, 15))
        self.left.setArrowType(Qt.LeftArrow)

        self.horizontalLayout_3.addWidget(self.left)

        self.right = QToolButton(self.w_arrows)
        self.right.setObjectName(u"right")
        self.right.setMinimumSize(QSize(14, 14))
        self.right.setMaximumSize(QSize(14, 14))
        self.right.setArrowType(Qt.RightArrow)

        self.horizontalLayout_3.addWidget(self.right)


        self.horizontalLayout_5.addWidget(self.w_arrows)

        self.hs_lev_2 = QSpacerItem(1, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_5.addItem(self.hs_lev_2)


        self.verticalLayout_7.addWidget(self.image_levels_control)

        self.image_levels = QStackedWidget(self.w_image_levels)
        self.image_levels.setObjectName(u"image_levels")
        self.p_min_max = QWidget()
        self.p_min_max.setObjectName(u"p_min_max")
        self.verticalLayout_8 = QVBoxLayout(self.p_min_max)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.w_min_max = QWidget(self.p_min_max)
        self.w_min_max.setObjectName(u"w_min_max")
        self.w_min_max.setMinimumSize(QSize(0, 0))
        self.w_min_max.setMaximumSize(QSize(16777215, 16777215))
        self.gridLayout_2 = QGridLayout(self.w_min_max)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 5, 0, 5)
        self.label_min = QLabel(self.w_min_max)
        self.label_min.setObjectName(u"label_min")
        sizePolicy2.setHeightForWidth(self.label_min.sizePolicy().hasHeightForWidth())
        self.label_min.setSizePolicy(sizePolicy2)
        self.label_min.setMinimumSize(QSize(0, 20))
        self.label_min.setMaximumSize(QSize(16777215, 20))
        self.label_min.setFont(font5)

        self.gridLayout_2.addWidget(self.label_min, 0, 0, 1, 1)

        self.spin_min = MyQDoubleSpin(self.w_min_max)
        self.spin_min.setObjectName(u"spin_min")
        self.spin_min.setMinimumSize(QSize(0, 24))
        self.spin_min.setMaximumSize(QSize(16777215, 24))
        self.spin_min.setFont(font)
        self.spin_min.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.gridLayout_2.addWidget(self.spin_min, 0, 2, 1, 1)

        self.slider_max = QSlider(self.w_min_max)
        self.slider_max.setObjectName(u"slider_max")
        self.slider_max.setMinimumSize(QSize(0, 24))
        self.slider_max.setMaximumSize(QSize(16777215, 24))
        self.slider_max.setOrientation(Qt.Horizontal)

        self.gridLayout_2.addWidget(self.slider_max, 1, 1, 1, 1)

        self.label_max = QLabel(self.w_min_max)
        self.label_max.setObjectName(u"label_max")
        sizePolicy2.setHeightForWidth(self.label_max.sizePolicy().hasHeightForWidth())
        self.label_max.setSizePolicy(sizePolicy2)
        self.label_max.setMinimumSize(QSize(0, 20))
        self.label_max.setMaximumSize(QSize(16777215, 20))
        self.label_max.setFont(font5)

        self.gridLayout_2.addWidget(self.label_max, 1, 0, 1, 1)

        self.spin_max = MyQDoubleSpin(self.w_min_max)
        self.spin_max.setObjectName(u"spin_max")
        self.spin_max.setMinimumSize(QSize(0, 24))
        self.spin_max.setMaximumSize(QSize(16777215, 24))
        self.spin_max.setFont(font)
        self.spin_max.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.gridLayout_2.addWidget(self.spin_max, 1, 2, 1, 1)

        self.slider_min = QSlider(self.w_min_max)
        self.slider_min.setObjectName(u"slider_min")
        self.slider_min.setMinimumSize(QSize(0, 24))
        self.slider_min.setMaximumSize(QSize(16777215, 24))
        self.slider_min.setOrientation(Qt.Horizontal)

        self.gridLayout_2.addWidget(self.slider_min, 0, 1, 1, 1)

        self.slider_mean = QSlider(self.w_min_max)
        self.slider_mean.setObjectName(u"slider_mean")
        self.slider_mean.setMinimumSize(QSize(0, 24))
        self.slider_mean.setMaximumSize(QSize(16777215, 24))
        self.slider_mean.setOrientation(Qt.Horizontal)

        self.gridLayout_2.addWidget(self.slider_mean, 2, 1, 1, 1)

        self.label_mean = QLabel(self.w_min_max)
        self.label_mean.setObjectName(u"label_mean")
        sizePolicy2.setHeightForWidth(self.label_mean.sizePolicy().hasHeightForWidth())
        self.label_mean.setSizePolicy(sizePolicy2)
        self.label_mean.setMinimumSize(QSize(0, 20))
        self.label_mean.setMaximumSize(QSize(16777215, 20))
        self.label_mean.setFont(font5)

        self.gridLayout_2.addWidget(self.label_mean, 2, 0, 1, 1)

        self.spin_mean = MyQDoubleSpin(self.w_min_max)
        self.spin_mean.setObjectName(u"spin_mean")
        self.spin_mean.setMinimumSize(QSize(0, 24))
        self.spin_mean.setMaximumSize(QSize(16777215, 24))
        self.spin_mean.setFont(font)
        self.spin_mean.setWrapping(False)
        self.spin_mean.setFrame(True)
        self.spin_mean.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_mean.setAccelerated(True)
        self.spin_mean.setProperty("showGroupSeparator", False)

        self.gridLayout_2.addWidget(self.spin_mean, 2, 2, 1, 1)

        self.label_range = QLabel(self.w_min_max)
        self.label_range.setObjectName(u"label_range")
        sizePolicy2.setHeightForWidth(self.label_range.sizePolicy().hasHeightForWidth())
        self.label_range.setSizePolicy(sizePolicy2)
        self.label_range.setMinimumSize(QSize(0, 20))
        self.label_range.setMaximumSize(QSize(16777215, 20))
        self.label_range.setFont(font5)

        self.gridLayout_2.addWidget(self.label_range, 3, 0, 1, 1)

        self.slider_range = QSlider(self.w_min_max)
        self.slider_range.setObjectName(u"slider_range")
        self.slider_range.setMinimumSize(QSize(0, 24))
        self.slider_range.setMaximumSize(QSize(16777215, 24))
        self.slider_range.setOrientation(Qt.Horizontal)

        self.gridLayout_2.addWidget(self.slider_range, 3, 1, 1, 1)

        self.spin_range = MyQDoubleSpin(self.w_min_max)
        self.spin_range.setObjectName(u"spin_range")
        self.spin_range.setMinimumSize(QSize(0, 24))
        self.spin_range.setMaximumSize(QSize(16777215, 24))
        self.spin_range.setFont(font)
        self.spin_range.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.gridLayout_2.addWidget(self.spin_range, 3, 2, 1, 1)

        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 1)

        self.verticalLayout_8.addWidget(self.w_min_max)

        self.image_levels.addWidget(self.p_min_max)
        self.p_limits = QWidget()
        self.p_limits.setObjectName(u"p_limits")
        self.verticalLayout_9 = QVBoxLayout(self.p_limits)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.w_mean_range = QWidget(self.p_limits)
        self.w_mean_range.setObjectName(u"w_mean_range")
        self.w_mean_range.setMinimumSize(QSize(0, 110))
        self.gridLayout = QGridLayout(self.w_mean_range)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setContentsMargins(0, 10, 0, 10)
        self.spin_xmin = MyQDoubleSpin(self.w_mean_range)
        self.spin_xmin.setObjectName(u"spin_xmin")
        self.spin_xmin.setMinimumSize(QSize(0, 24))
        self.spin_xmin.setMaximumSize(QSize(16777215, 24))
        self.spin_xmin.setFont(font)
        self.spin_xmin.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_xmin.setDecimals(4)
        self.spin_xmin.setMinimum(-1000000000.000000000000000)
        self.spin_xmin.setMaximum(1000000000.000000000000000)
        self.spin_xmin.setSingleStep(0.010000000000000)

        self.gridLayout.addWidget(self.spin_xmin, 1, 1, 1, 1)

        self.label_lim_min = QLabel(self.w_mean_range)
        self.label_lim_min.setObjectName(u"label_lim_min")
        sizePolicy2.setHeightForWidth(self.label_lim_min.sizePolicy().hasHeightForWidth())
        self.label_lim_min.setSizePolicy(sizePolicy2)
        self.label_lim_min.setMinimumSize(QSize(50, 20))
        self.label_lim_min.setMaximumSize(QSize(16777215, 20))
        self.label_lim_min.setFont(font5)

        self.gridLayout.addWidget(self.label_lim_min, 0, 1, 1, 1)

        self.label_lim_empty = QLabel(self.w_mean_range)
        self.label_lim_empty.setObjectName(u"label_lim_empty")
        sizePolicy2.setHeightForWidth(self.label_lim_empty.sizePolicy().hasHeightForWidth())
        self.label_lim_empty.setSizePolicy(sizePolicy2)
        self.label_lim_empty.setMinimumSize(QSize(50, 20))
        self.label_lim_empty.setMaximumSize(QSize(16777215, 20))
        self.label_lim_empty.setFont(font5)
        self.label_lim_empty.setLayoutDirection(Qt.LeftToRight)
        self.label_lim_empty.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_lim_empty, 0, 0, 1, 1)

        self.label_lim_max = QLabel(self.w_mean_range)
        self.label_lim_max.setObjectName(u"label_lim_max")
        sizePolicy2.setHeightForWidth(self.label_lim_max.sizePolicy().hasHeightForWidth())
        self.label_lim_max.setSizePolicy(sizePolicy2)
        self.label_lim_max.setMinimumSize(QSize(50, 20))
        self.label_lim_max.setMaximumSize(QSize(16777215, 20))
        self.label_lim_max.setFont(font5)

        self.gridLayout.addWidget(self.label_lim_max, 0, 2, 1, 1)

        self.spin_xmax = MyQDoubleSpin(self.w_mean_range)
        self.spin_xmax.setObjectName(u"spin_xmax")
        self.spin_xmax.setMinimumSize(QSize(0, 24))
        self.spin_xmax.setMaximumSize(QSize(16777215, 24))
        self.spin_xmax.setFont(font)
        self.spin_xmax.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_xmax.setProperty("showGroupSeparator", False)
        self.spin_xmax.setDecimals(4)
        self.spin_xmax.setMinimum(-1000000000.000000000000000)
        self.spin_xmax.setMaximum(1000000000.000000000000000)
        self.spin_xmax.setSingleStep(0.010000000000000)

        self.gridLayout.addWidget(self.spin_xmax, 1, 2, 1, 1)

        self.label_xlim = QLabel(self.w_mean_range)
        self.label_xlim.setObjectName(u"label_xlim")
        sizePolicy2.setHeightForWidth(self.label_xlim.sizePolicy().hasHeightForWidth())
        self.label_xlim.setSizePolicy(sizePolicy2)
        self.label_xlim.setMinimumSize(QSize(50, 20))
        self.label_xlim.setMaximumSize(QSize(16777215, 20))
        self.label_xlim.setFont(font5)
        self.label_xlim.setLayoutDirection(Qt.LeftToRight)
        self.label_xlim.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_xlim, 1, 0, 1, 1)

        self.label_ylim = QLabel(self.w_mean_range)
        self.label_ylim.setObjectName(u"label_ylim")
        sizePolicy2.setHeightForWidth(self.label_ylim.sizePolicy().hasHeightForWidth())
        self.label_ylim.setSizePolicy(sizePolicy2)
        self.label_ylim.setMinimumSize(QSize(50, 20))
        self.label_ylim.setMaximumSize(QSize(16777215, 20))
        self.label_ylim.setFont(font5)
        self.label_ylim.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_ylim, 2, 0, 1, 1)

        self.spin_ymin = MyQDoubleSpin(self.w_mean_range)
        self.spin_ymin.setObjectName(u"spin_ymin")
        self.spin_ymin.setMinimumSize(QSize(0, 24))
        self.spin_ymin.setMaximumSize(QSize(16777215, 24))
        self.spin_ymin.setFont(font)
        self.spin_ymin.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_ymin.setDecimals(4)
        self.spin_ymin.setMinimum(-1000000000.000000000000000)
        self.spin_ymin.setMaximum(1000000000.000000000000000)
        self.spin_ymin.setSingleStep(0.010000000000000)

        self.gridLayout.addWidget(self.spin_ymin, 2, 1, 1, 1)

        self.spin_ymax = MyQDoubleSpin(self.w_mean_range)
        self.spin_ymax.setObjectName(u"spin_ymax")
        self.spin_ymax.setMinimumSize(QSize(0, 24))
        self.spin_ymax.setMaximumSize(QSize(16777215, 24))
        self.spin_ymax.setFont(font)
        self.spin_ymax.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_ymax.setDecimals(4)
        self.spin_ymax.setMinimum(-1000000000.000000000000000)
        self.spin_ymax.setMaximum(1000000000.000000000000000)
        self.spin_ymax.setSingleStep(0.010000000000000)

        self.gridLayout.addWidget(self.spin_ymax, 2, 2, 1, 1)


        self.verticalLayout_9.addWidget(self.w_mean_range)

        self.image_levels.addWidget(self.p_limits)
        self.p_contour_quiver = QWidget()
        self.p_contour_quiver.setObjectName(u"p_contour_quiver")
        self.verticalLayout_10 = QVBoxLayout(self.p_contour_quiver)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.w_contour_quiver = QWidget(self.p_contour_quiver)
        self.w_contour_quiver.setObjectName(u"w_contour_quiver")
        self.w_contour_quiver.setMinimumSize(QSize(0, 110))
        self.gridLayout_6 = QGridLayout(self.w_contour_quiver)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setHorizontalSpacing(5)
        self.gridLayout_6.setVerticalSpacing(10)
        self.gridLayout_6.setContentsMargins(0, 10, 0, 10)
        self.label_nclev = QLabel(self.w_contour_quiver)
        self.label_nclev.setObjectName(u"label_nclev")
        sizePolicy2.setHeightForWidth(self.label_nclev.sizePolicy().hasHeightForWidth())
        self.label_nclev.setSizePolicy(sizePolicy2)
        self.label_nclev.setMinimumSize(QSize(0, 20))
        self.label_nclev.setMaximumSize(QSize(16777215, 20))
        self.label_nclev.setFont(font5)

        self.gridLayout_6.addWidget(self.label_nclev, 0, 0, 1, 1)

        self.spin_vecsize = MyQDoubleSpin(self.w_contour_quiver)
        self.spin_vecsize.setObjectName(u"spin_vecsize")
        self.spin_vecsize.setMinimumSize(QSize(0, 24))
        self.spin_vecsize.setMaximumSize(QSize(16777215, 24))
        self.spin_vecsize.setFont(font)
        self.spin_vecsize.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_vecsize.setMinimum(0.100000000000000)
        self.spin_vecsize.setMaximum(25.000000000000000)
        self.spin_vecsize.setSingleStep(0.010000000000000)
        self.spin_vecsize.setValue(1.000000000000000)

        self.gridLayout_6.addWidget(self.spin_vecsize, 1, 2, 1, 1)

        self.spin_streamdens = MyQDoubleSpin(self.w_contour_quiver)
        self.spin_streamdens.setObjectName(u"spin_streamdens")
        self.spin_streamdens.setMinimumSize(QSize(0, 24))
        self.spin_streamdens.setMaximumSize(QSize(16777215, 24))
        self.spin_streamdens.setFont(font)
        self.spin_streamdens.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_streamdens.setMinimum(0.100000000000000)
        self.spin_streamdens.setMaximum(3.000000000000000)
        self.spin_streamdens.setSingleStep(0.010000000000000)
        self.spin_streamdens.setValue(1.000000000000000)

        self.gridLayout_6.addWidget(self.spin_streamdens, 3, 2, 1, 1)

        self.slider_vecsize = QSlider(self.w_contour_quiver)
        self.slider_vecsize.setObjectName(u"slider_vecsize")
        self.slider_vecsize.setMinimumSize(QSize(0, 24))
        self.slider_vecsize.setMaximumSize(QSize(16777215, 24))
        self.slider_vecsize.setOrientation(Qt.Horizontal)

        self.gridLayout_6.addWidget(self.slider_vecsize, 1, 1, 1, 1)

        self.slider_streamdens = QSlider(self.w_contour_quiver)
        self.slider_streamdens.setObjectName(u"slider_streamdens")
        self.slider_streamdens.setMinimumSize(QSize(0, 24))
        self.slider_streamdens.setMaximumSize(QSize(16777215, 24))
        self.slider_streamdens.setOrientation(Qt.Horizontal)

        self.gridLayout_6.addWidget(self.slider_streamdens, 3, 1, 1, 1)

        self.label_vecsize = QLabel(self.w_contour_quiver)
        self.label_vecsize.setObjectName(u"label_vecsize")
        sizePolicy2.setHeightForWidth(self.label_vecsize.sizePolicy().hasHeightForWidth())
        self.label_vecsize.setSizePolicy(sizePolicy2)
        self.label_vecsize.setMinimumSize(QSize(0, 20))
        self.label_vecsize.setMaximumSize(QSize(16777215, 20))
        self.label_vecsize.setFont(font5)

        self.gridLayout_6.addWidget(self.label_vecsize, 1, 0, 1, 1)

        self.spin_nclev = MyQSpin(self.w_contour_quiver)
        self.spin_nclev.setObjectName(u"spin_nclev")
        self.spin_nclev.setMinimumSize(QSize(0, 24))
        self.spin_nclev.setMaximumSize(QSize(16777215, 24))
        self.spin_nclev.setFont(font)
        self.spin_nclev.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_nclev.setMinimum(3)
        self.spin_nclev.setMaximum(128)

        self.gridLayout_6.addWidget(self.spin_nclev, 0, 2, 1, 1)

        self.slider_nclev = QSlider(self.w_contour_quiver)
        self.slider_nclev.setObjectName(u"slider_nclev")
        self.slider_nclev.setMinimumSize(QSize(0, 24))
        self.slider_nclev.setMaximumSize(QSize(16777215, 24))
        self.slider_nclev.setOrientation(Qt.Horizontal)

        self.gridLayout_6.addWidget(self.slider_nclev, 0, 1, 1, 1)

        self.label_streamdens = QLabel(self.w_contour_quiver)
        self.label_streamdens.setObjectName(u"label_streamdens")
        sizePolicy2.setHeightForWidth(self.label_streamdens.sizePolicy().hasHeightForWidth())
        self.label_streamdens.setSizePolicy(sizePolicy2)
        self.label_streamdens.setMinimumSize(QSize(0, 20))
        self.label_streamdens.setMaximumSize(QSize(16777215, 20))
        self.label_streamdens.setFont(font5)

        self.gridLayout_6.addWidget(self.label_streamdens, 3, 0, 1, 1)

        self.label_vecspac = QLabel(self.w_contour_quiver)
        self.label_vecspac.setObjectName(u"label_vecspac")
        sizePolicy2.setHeightForWidth(self.label_vecspac.sizePolicy().hasHeightForWidth())
        self.label_vecspac.setSizePolicy(sizePolicy2)
        self.label_vecspac.setMinimumSize(QSize(0, 20))
        self.label_vecspac.setMaximumSize(QSize(16777215, 20))
        self.label_vecspac.setFont(font5)

        self.gridLayout_6.addWidget(self.label_vecspac, 2, 0, 1, 1)

        self.slider_vecspac = QSlider(self.w_contour_quiver)
        self.slider_vecspac.setObjectName(u"slider_vecspac")
        self.slider_vecspac.setMinimumSize(QSize(0, 24))
        self.slider_vecspac.setMaximumSize(QSize(16777215, 24))
        self.slider_vecspac.setOrientation(Qt.Horizontal)

        self.gridLayout_6.addWidget(self.slider_vecspac, 2, 1, 1, 1)

        self.spin_vecspac = MyQSpin(self.w_contour_quiver)
        self.spin_vecspac.setObjectName(u"spin_vecspac")
        self.spin_vecspac.setMinimumSize(QSize(0, 24))
        self.spin_vecspac.setMaximumSize(QSize(16777215, 24))
        self.spin_vecspac.setFont(font)
        self.spin_vecspac.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_vecspac.setMinimum(1)

        self.gridLayout_6.addWidget(self.spin_vecspac, 2, 2, 1, 1)


        self.verticalLayout_10.addWidget(self.w_contour_quiver)

        self.image_levels.addWidget(self.p_contour_quiver)

        self.verticalLayout_7.addWidget(self.image_levels)


        self.horizontalLayout.addWidget(self.w_image_levels)

        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)

        self.verticalLayout_2.addWidget(self.w_Plot_Contour_Map)


        self.verticalLayout_24.addWidget(self.Plot_tools)


        self.lay_w_Plot.addWidget(self.CollapBox_PlotTools)

        self.w_field_number = QWidget(self.w_plot)
        self.w_field_number.setObjectName(u"w_field_number")
        self.w_field_number.setMinimumSize(QSize(0, 24))
        self.w_field_number.setMaximumSize(QSize(16777215, 24))
        self.w_field_number.setSizeIncrement(QSize(0, 0))
        self.w_field_number.setBaseSize(QSize(0, 0))
        self.horizontalLayout_7 = QHBoxLayout(self.w_field_number)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_field_number = QLabel(self.w_field_number)
        self.label_field_number.setObjectName(u"label_field_number")
        sizePolicy2.setHeightForWidth(self.label_field_number.sizePolicy().hasHeightForWidth())
        self.label_field_number.setSizePolicy(sizePolicy2)
        self.label_field_number.setMinimumSize(QSize(0, 24))
        self.label_field_number.setMaximumSize(QSize(16777215, 24))
        self.label_field_number.setFont(font5)
        self.label_field_number.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_7.addWidget(self.label_field_number)

        self.spin_field_number = MyQSpin(self.w_field_number)
        self.spin_field_number.setObjectName(u"spin_field_number")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.spin_field_number.sizePolicy().hasHeightForWidth())
        self.spin_field_number.setSizePolicy(sizePolicy4)
        self.spin_field_number.setMinimumSize(QSize(0, 24))
        self.spin_field_number.setMaximumSize(QSize(60, 24))
        self.spin_field_number.setFont(font)
        self.spin_field_number.setFocusPolicy(Qt.WheelFocus)
        self.spin_field_number.setMinimum(-1)
        self.spin_field_number.setMaximum(99999)
        self.spin_field_number.setValue(0)

        self.horizontalLayout_7.addWidget(self.spin_field_number)

        self.hs_field_number = QSpacerItem(15, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_7.addItem(self.hs_field_number)

        self.label_frame_number = QLabel(self.w_field_number)
        self.label_frame_number.setObjectName(u"label_frame_number")
        sizePolicy2.setHeightForWidth(self.label_frame_number.sizePolicy().hasHeightForWidth())
        self.label_frame_number.setSizePolicy(sizePolicy2)
        self.label_frame_number.setMinimumSize(QSize(0, 24))
        self.label_frame_number.setMaximumSize(QSize(16777215, 24))
        self.label_frame_number.setFont(font5)
        self.label_frame_number.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_7.addWidget(self.label_frame_number)

        self.spin_frame_number = MyQSpin(self.w_field_number)
        self.spin_frame_number.setObjectName(u"spin_frame_number")
        sizePolicy4.setHeightForWidth(self.spin_frame_number.sizePolicy().hasHeightForWidth())
        self.spin_frame_number.setSizePolicy(sizePolicy4)
        self.spin_frame_number.setMinimumSize(QSize(0, 24))
        self.spin_frame_number.setMaximumSize(QSize(40, 24))
        self.spin_frame_number.setFont(font)
        self.spin_frame_number.setFocusPolicy(Qt.WheelFocus)
        self.spin_frame_number.setMinimum(0)
        self.spin_frame_number.setMaximum(1)
        self.spin_frame_number.setValue(0)

        self.horizontalLayout_7.addWidget(self.spin_frame_number)

        self.hs_frame_number = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_7.addItem(self.hs_frame_number)

        self.name_var = QLabel(self.w_field_number)
        self.name_var.setObjectName(u"name_var")
        self.name_var.setMinimumSize(QSize(0, 22))
        self.name_var.setMaximumSize(QSize(16777215, 22))
        font6 = QFont()
        font6.setPointSize(10)
        self.name_var.setFont(font6)
        self.name_var.setMargin(0)

        self.horizontalLayout_7.addWidget(self.name_var)


        self.lay_w_Plot.addWidget(self.w_field_number)

        self.plot = MplCanvas(self.w_plot)
        self.plot.setObjectName(u"plot")
        self.plot.setFocusPolicy(Qt.ClickFocus)

        self.lay_w_Plot.addWidget(self.plot)

        self.lay_w_Plot.setStretch(1, 1)
        self.lay_w_Plot.setStretch(2, 1)
        self.plot.raise_()
        self.CollapBox_PlotTools.raise_()
        self.w_field_number.raise_()

        self.verticalLayout.addWidget(self.w_plot)

        QWidget.setTabOrder(self.button_back, self.button_forward)
        QWidget.setTabOrder(self.button_forward, self.button_close_tab)
        QWidget.setTabOrder(self.button_close_tab, self.button_showIW)
        QWidget.setTabOrder(self.button_showIW, self.button_showMTF)
        QWidget.setTabOrder(self.button_showMTF, self.button_subMIN)
        QWidget.setTabOrder(self.button_subMIN, self.combo_map_var)
        QWidget.setTabOrder(self.combo_map_var, self.combo_field_rep)
        QWidget.setTabOrder(self.combo_field_rep, self.button_restore)
        QWidget.setTabOrder(self.button_restore, self.button_resize)
        QWidget.setTabOrder(self.button_resize, self.button_invert_y)
        QWidget.setTabOrder(self.button_invert_y, self.left)
        QWidget.setTabOrder(self.left, self.right)
        QWidget.setTabOrder(self.right, self.slider_min)
        QWidget.setTabOrder(self.slider_min, self.spin_min)
        QWidget.setTabOrder(self.spin_min, self.slider_max)
        QWidget.setTabOrder(self.slider_max, self.spin_max)
        QWidget.setTabOrder(self.spin_max, self.slider_mean)
        QWidget.setTabOrder(self.slider_mean, self.spin_mean)
        QWidget.setTabOrder(self.spin_mean, self.slider_range)
        QWidget.setTabOrder(self.slider_range, self.spin_range)
        QWidget.setTabOrder(self.spin_range, self.spin_xmin)
        QWidget.setTabOrder(self.spin_xmin, self.spin_xmax)
        QWidget.setTabOrder(self.spin_xmax, self.spin_ymin)
        QWidget.setTabOrder(self.spin_ymin, self.spin_ymax)
        QWidget.setTabOrder(self.spin_ymax, self.slider_nclev)
        QWidget.setTabOrder(self.slider_nclev, self.spin_nclev)
        QWidget.setTabOrder(self.spin_nclev, self.slider_vecsize)
        QWidget.setTabOrder(self.slider_vecsize, self.spin_vecsize)
        QWidget.setTabOrder(self.spin_vecsize, self.slider_vecspac)
        QWidget.setTabOrder(self.slider_vecspac, self.spin_vecspac)
        QWidget.setTabOrder(self.spin_vecspac, self.slider_streamdens)
        QWidget.setTabOrder(self.slider_streamdens, self.spin_streamdens)
        QWidget.setTabOrder(self.spin_streamdens, self.spin_field_number)
        QWidget.setTabOrder(self.spin_field_number, self.spin_frame_number)

        self.retranslateUi(VisTab)

        self.image_levels.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(VisTab)
    # setupUi

    def retranslateUi(self, VisTab):
        VisTab.setWindowTitle(QCoreApplication.translate("VisTab", u"VisTab", None))
        self.icon.setText("")
        self.name_tab.setText(QCoreApplication.translate("VisTab", u" Vis", None))
        self.label_number.setText(QCoreApplication.translate("VisTab", u"1", None))
#if QT_CONFIG(tooltip)
        self.button_back.setToolTip(QCoreApplication.translate("VisTab", u"Undo", None))
#endif // QT_CONFIG(tooltip)
        self.button_back.setText("")
#if QT_CONFIG(tooltip)
        self.button_forward.setToolTip(QCoreApplication.translate("VisTab", u"Redo", None))
#endif // QT_CONFIG(tooltip)
        self.button_forward.setText("")
#if QT_CONFIG(tooltip)
        self.button_close_tab.setToolTip(QCoreApplication.translate("VisTab", u"Close tab", None))
#endif // QT_CONFIG(tooltip)
        self.button_close_tab.setText("")
#if QT_CONFIG(shortcut)
        self.button_close_tab.setShortcut(QCoreApplication.translate("VisTab", u"Alt+K", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.tool_CollapBox_PlotTools.setToolTip(QCoreApplication.translate("VisTab", u"Plot tools option box", None))
#endif // QT_CONFIG(tooltip)
        self.tool_CollapBox_PlotTools.setText(QCoreApplication.translate("VisTab", u"Plot tools", None))
#if QT_CONFIG(tooltip)
        self.push_CollapBox_PlotTools.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.push_CollapBox_PlotTools.setText("")
#if QT_CONFIG(tooltip)
        self.button_showIW.setToolTip(QCoreApplication.translate("VisTab", u"Show Interrogation Window scheme", None))
#endif // QT_CONFIG(tooltip)
        self.button_showIW.setText(QCoreApplication.translate("VisTab", u"IW", None))
#if QT_CONFIG(shortcut)
        self.button_showIW.setShortcut(QCoreApplication.translate("VisTab", u"Ctrl+Alt+W", None))
#endif // QT_CONFIG(shortcut)
        self.button_showMTF.setText(QCoreApplication.translate("VisTab", u"MTF", None))
        self.button_subMIN.setText(QCoreApplication.translate("VisTab", u"- MIN", None))
#if QT_CONFIG(shortcut)
        self.button_subMIN.setShortcut(QCoreApplication.translate("VisTab", u"Ctrl+Alt+M", None))
#endif // QT_CONFIG(shortcut)
        self.label_map_var.setText(QCoreApplication.translate("VisTab", u"Map variable", None))
        self.combo_map_var.setItemText(0, QCoreApplication.translate("VisTab", u"intensity (frame 0)", None))
        self.combo_map_var.setItemText(1, QCoreApplication.translate("VisTab", u"intensity (frame 1)", None))
        self.combo_map_var.setItemText(2, QCoreApplication.translate("VisTab", u"magnitude", None))
        self.combo_map_var.setItemText(3, QCoreApplication.translate("VisTab", u"u", None))
        self.combo_map_var.setItemText(4, QCoreApplication.translate("VisTab", u"v", None))
        self.combo_map_var.setItemText(5, QCoreApplication.translate("VisTab", u"S/N", None))
        self.combo_map_var.setItemText(6, QCoreApplication.translate("VisTab", u"Info", None))

#if QT_CONFIG(tooltip)
        self.combo_map_var.setToolTip(QCoreApplication.translate("VisTab", u"Select the variable to display", None))
#endif // QT_CONFIG(tooltip)
        self.label_field_rep.setText(QCoreApplication.translate("VisTab", u"Field representation", None))
        self.combo_field_rep.setItemText(0, QCoreApplication.translate("VisTab", u"-", None))
        self.combo_field_rep.setItemText(1, QCoreApplication.translate("VisTab", u"vectors", None))
        self.combo_field_rep.setItemText(2, QCoreApplication.translate("VisTab", u"streamlines", None))

#if QT_CONFIG(tooltip)
        self.combo_field_rep.setToolTip(QCoreApplication.translate("VisTab", u"Select a method to show the morphology of the velocity field", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.button_restore.setToolTip(QCoreApplication.translate("VisTab", u"Restore default levels for the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.button_restore.setText("")
#if QT_CONFIG(tooltip)
        self.button_resize.setToolTip(QCoreApplication.translate("VisTab", u"Resize the dispalyed map", None))
#endif // QT_CONFIG(tooltip)
        self.button_resize.setText("")
#if QT_CONFIG(tooltip)
        self.button_invert_y.setToolTip(QCoreApplication.translate("VisTab", u"Invert direction of y-axis", None))
#endif // QT_CONFIG(tooltip)
        self.button_invert_y.setText("")
        self.label_title.setText(QCoreApplication.translate("VisTab", u"Settings", None))
        self.left.setText(QCoreApplication.translate("VisTab", u"...", None))
        self.right.setText(QCoreApplication.translate("VisTab", u"...", None))
#if QT_CONFIG(tooltip)
        self.label_min.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the minimum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_min.setText(QCoreApplication.translate("VisTab", u"min", None))
#if QT_CONFIG(tooltip)
        self.spin_min.setToolTip(QCoreApplication.translate("VisTab", u"Set the minimum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slider_max.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the maximum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_max.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the maximum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_max.setText(QCoreApplication.translate("VisTab", u"max", None))
#if QT_CONFIG(tooltip)
        self.spin_max.setToolTip(QCoreApplication.translate("VisTab", u"Set the maximum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slider_min.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the minimum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slider_mean.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the average value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_mean.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the average value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_mean.setText(QCoreApplication.translate("VisTab", u"mean", None))
#if QT_CONFIG(tooltip)
        self.spin_mean.setToolTip(QCoreApplication.translate("VisTab", u"Set the average value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_range.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_range.setText(QCoreApplication.translate("VisTab", u"range", None))
#if QT_CONFIG(tooltip)
        self.slider_range.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.spin_range.setToolTip(QCoreApplication.translate("VisTab", u"Set the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.spin_xmin.setToolTip(QCoreApplication.translate("VisTab", u"Set the minimum X limit", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_lim_min.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the minimum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_lim_min.setText(QCoreApplication.translate("VisTab", u"min", None))
#if QT_CONFIG(tooltip)
        self.label_lim_empty.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the minimum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_lim_empty.setText(QCoreApplication.translate("VisTab", u"Limits ", None))
#if QT_CONFIG(tooltip)
        self.label_lim_max.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the minimum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_lim_max.setText(QCoreApplication.translate("VisTab", u"max", None))
#if QT_CONFIG(tooltip)
        self.spin_xmax.setToolTip(QCoreApplication.translate("VisTab", u"Set the maximum X limit", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_xlim.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the minimum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_xlim.setText(QCoreApplication.translate("VisTab", u"X: ", None))
#if QT_CONFIG(tooltip)
        self.label_ylim.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the minimum value of the range covered by the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_ylim.setText(QCoreApplication.translate("VisTab", u"Y: ", None))
#if QT_CONFIG(tooltip)
        self.spin_ymin.setToolTip(QCoreApplication.translate("VisTab", u"Set the minimum Y limit", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.spin_ymax.setToolTip(QCoreApplication.translate("VisTab", u"Set the maximum Y limit", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_nclev.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the number of colour levels in the colormap", None))
#endif // QT_CONFIG(tooltip)
        self.label_nclev.setText(QCoreApplication.translate("VisTab", u"# colour levels", None))
#if QT_CONFIG(tooltip)
        self.spin_vecsize.setToolTip(QCoreApplication.translate("VisTab", u"Set the size of the vectors", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.spin_streamdens.setToolTip(QCoreApplication.translate("VisTab", u"Set the density of the streamlines", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slider_vecsize.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the size of the vectors", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slider_streamdens.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the density of the streamlines", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_vecsize.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the size of the vectors", None))
#endif // QT_CONFIG(tooltip)
        self.label_vecsize.setText(QCoreApplication.translate("VisTab", u"vector size", None))
#if QT_CONFIG(tooltip)
        self.spin_nclev.setToolTip(QCoreApplication.translate("VisTab", u"Set the number of colour levels in the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slider_nclev.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the number of colour levels in the colormap", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_streamdens.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the density of the streamlines", None))
#endif // QT_CONFIG(tooltip)
        self.label_streamdens.setText(QCoreApplication.translate("VisTab", u"streamline density", None))
#if QT_CONFIG(tooltip)
        self.label_vecspac.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the size of the vectors", None))
#endif // QT_CONFIG(tooltip)
        self.label_vecspac.setText(QCoreApplication.translate("VisTab", u"vector spacing", None))
#if QT_CONFIG(tooltip)
        self.slider_vecspac.setToolTip(QCoreApplication.translate("VisTab", u"Adjust the spacing of the vectors", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.spin_vecspac.setToolTip(QCoreApplication.translate("VisTab", u"Set the spacing of the vectors", None))
#endif // QT_CONFIG(tooltip)
        self.label_field_number.setText(QCoreApplication.translate("VisTab", u"field #  ", None))
#if QT_CONFIG(tooltip)
        self.spin_field_number.setToolTip(QCoreApplication.translate("VisTab", u"Set the number of field to be displayed in Vis. Set the value to -1 to visualize the minimum images and the average velocity field", None))
#endif // QT_CONFIG(tooltip)
        self.label_frame_number.setText(QCoreApplication.translate("VisTab", u"frame  ", None))
#if QT_CONFIG(tooltip)
        self.spin_frame_number.setToolTip(QCoreApplication.translate("VisTab", u"<html><head/><body><p>Set the number of frame to be displayed. 0 for the first frame, 1 for the second one </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.name_var.setText(QCoreApplication.translate("VisTab", u"Input file: *", None))
    # retranslateUi

