
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-05T11:22:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ebdd67f4fb32ad997f07f78bea34e8f28a9d8d2",
 "version": "2.29.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
