import pandas as pd
from ._stat_sig_test import StatSigTest as StatSigTest

class StatSig:
    stat_sig_test: StatSigTest
    summary_table: pd.DataFrame
    def __init__(self, stat_sig_test, summary_table) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
