# coding: utf-8

"""
    Cachet Status Page API

    A java-friendly swagger documentation file based on the documentation for the Cachet Status Page https://cachethq.io/  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComponentResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'description': 'str',
        'link': 'str',
        'status': 'int',
        'order': 'int',
        'group_id': 'int',
        'created_at': 'str',
        'updated_at': 'str',
        'deleted_at': 'str',
        'status_name': 'str',
        'tags': 'Tag'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'link': 'link',
        'status': 'status',
        'order': 'order',
        'group_id': 'group_id',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'deleted_at': 'deleted_at',
        'status_name': 'status_name',
        'tags': 'tags'
    }

    def __init__(self, id=None, name=None, description=None, link=None, status=None, order=None, group_id=None, created_at=None, updated_at=None, deleted_at=None, status_name=None, tags=None):  # noqa: E501
        """ComponentResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._link = None
        self._status = None
        self._order = None
        self._group_id = None
        self._created_at = None
        self._updated_at = None
        self._deleted_at = None
        self._status_name = None
        self._tags = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if link is not None:
            self.link = link
        if status is not None:
            self.status = status
        if order is not None:
            self.order = order
        if group_id is not None:
            self.group_id = group_id
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if deleted_at is not None:
            self.deleted_at = deleted_at
        if status_name is not None:
            self.status_name = status_name
        if tags is not None:
            self.tags = tags

    @property
    def id(self):
        """Gets the id of this ComponentResponse.  # noqa: E501


        :return: The id of this ComponentResponse.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ComponentResponse.


        :param id: The id of this ComponentResponse.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ComponentResponse.  # noqa: E501


        :return: The name of this ComponentResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ComponentResponse.


        :param name: The name of this ComponentResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this ComponentResponse.  # noqa: E501


        :return: The description of this ComponentResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ComponentResponse.


        :param description: The description of this ComponentResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def link(self):
        """Gets the link of this ComponentResponse.  # noqa: E501


        :return: The link of this ComponentResponse.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this ComponentResponse.


        :param link: The link of this ComponentResponse.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def status(self):
        """Gets the status of this ComponentResponse.  # noqa: E501


        :return: The status of this ComponentResponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ComponentResponse.


        :param status: The status of this ComponentResponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def order(self):
        """Gets the order of this ComponentResponse.  # noqa: E501


        :return: The order of this ComponentResponse.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this ComponentResponse.


        :param order: The order of this ComponentResponse.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def group_id(self):
        """Gets the group_id of this ComponentResponse.  # noqa: E501


        :return: The group_id of this ComponentResponse.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this ComponentResponse.


        :param group_id: The group_id of this ComponentResponse.  # noqa: E501
        :type: int
        """

        self._group_id = group_id

    @property
    def created_at(self):
        """Gets the created_at of this ComponentResponse.  # noqa: E501


        :return: The created_at of this ComponentResponse.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ComponentResponse.


        :param created_at: The created_at of this ComponentResponse.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ComponentResponse.  # noqa: E501


        :return: The updated_at of this ComponentResponse.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ComponentResponse.


        :param updated_at: The updated_at of this ComponentResponse.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    @property
    def deleted_at(self):
        """Gets the deleted_at of this ComponentResponse.  # noqa: E501


        :return: The deleted_at of this ComponentResponse.  # noqa: E501
        :rtype: str
        """
        return self._deleted_at

    @deleted_at.setter
    def deleted_at(self, deleted_at):
        """Sets the deleted_at of this ComponentResponse.


        :param deleted_at: The deleted_at of this ComponentResponse.  # noqa: E501
        :type: str
        """

        self._deleted_at = deleted_at

    @property
    def status_name(self):
        """Gets the status_name of this ComponentResponse.  # noqa: E501


        :return: The status_name of this ComponentResponse.  # noqa: E501
        :rtype: str
        """
        return self._status_name

    @status_name.setter
    def status_name(self, status_name):
        """Sets the status_name of this ComponentResponse.


        :param status_name: The status_name of this ComponentResponse.  # noqa: E501
        :type: str
        """

        self._status_name = status_name

    @property
    def tags(self):
        """Gets the tags of this ComponentResponse.  # noqa: E501


        :return: The tags of this ComponentResponse.  # noqa: E501
        :rtype: Tag
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ComponentResponse.


        :param tags: The tags of this ComponentResponse.  # noqa: E501
        :type: Tag
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComponentResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComponentResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
