
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-09T03:34:20-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e026aba9726397bfec1ddbb9642ca4e19e40630",
 "version": "2.6.74"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
