from typing import Callable
from picoter_simulator.button import Button

class Display:
    def __init__(self, width: int, height: int) -> None: ...
    def _change_scale(self, **params: dict[str, int]) -> None: ...
    def _init_screen(self) -> None: ...
    def _update_ui(self) -> None: ...
    def _update_positioning(self) -> None: ...
    def _start(self, buttons: list[Button], mainfunc: Callable[[], None]) -> None: ...
    def fill(self, color: str) -> None: ...
    def drawRect(self, color: str, x: int, y: int, w: int, h: int) -> None: ...
