# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subjekt_pravnicka_osoba_zaklad import SubjektPravnickaOsobaZaklad

class TestSubjektPravnickaOsobaZaklad(unittest.TestCase):
    """SubjektPravnickaOsobaZaklad unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubjektPravnickaOsobaZaklad:
        """Test SubjektPravnickaOsobaZaklad
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubjektPravnickaOsobaZaklad`
        """
        model = SubjektPravnickaOsobaZaklad()
        if include_optional:
            return SubjektPravnickaOsobaZaklad(
                ico_zrizovatel = '0480728801234567',
                ico_nastupce = '0480728801234567',
                zpusob_zruseni_registrace = 56
            )
        else:
            return SubjektPravnickaOsobaZaklad(
        )
        """

    def testSubjektPravnickaOsobaZaklad(self):
        """Test SubjektPravnickaOsobaZaklad"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
