# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.statutatni_organ_rcns import StatutatniOrganRcns

class TestStatutatniOrganRcns(unittest.TestCase):
    """StatutatniOrganRcns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatutatniOrganRcns:
        """Test StatutatniOrganRcns
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatutatniOrganRcns`
        """
        model = StatutatniOrganRcns()
        if include_optional:
            return StatutatniOrganRcns(
                subjekt_cirkev = openapi_client.models.subjekt_cirkev.SubjektCirkev(),
                subjekt_svaz_cirkvi = openapi_client.models.subjekt_svaz_cirkvi.SubjektSvazCirkvi(),
                subjekt_pravnicka_osoba = openapi_client.models.subjekt_pravnicka_osoba.SubjektPravnickaOsoba()
            )
        else:
            return StatutatniOrganRcns(
        )
        """

    def testStatutatniOrganRcns(self):
        """Test StatutatniOrganRcns"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
