# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.odstepny_zavod_vr import OdstepnyZavodVr

class TestOdstepnyZavodVr(unittest.TestCase):
    """OdstepnyZavodVr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OdstepnyZavodVr:
        """Test OdstepnyZavodVr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OdstepnyZavodVr`
        """
        model = OdstepnyZavodVr()
        if include_optional:
            return OdstepnyZavodVr(
                datum_zapisu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_vymazu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                vedouci = [
                    openapi_client.models.angazma_osoba_vr.AngazmaOsobaVr()
                    ],
                ostatni_skutecnosti = [
                    openapi_client.models.obecny_text_vr.ObecnyTextVr()
                    ],
                cinnosti = openapi_client.models.cinnosti_vr.CinnostiVr(
                    predmet_podnikani = [
                        openapi_client.models.obecny_text_vr.ObecnyTextVr()
                        ], 
                    doplnkova_cinnost = [
                        openapi_client.models.obecny_text_vr.ObecnyTextVr()
                        ], 
                    predmet_cinnosti = [
                        openapi_client.models.obecny_text_vr.ObecnyTextVr()
                        ], 
                    ucel = [
                        openapi_client.models.obecny_text_vr.ObecnyTextVr()
                        ], ),
                ico = [
                    openapi_client.models.ico_vr.IcoVr()
                    ],
                sidlo = [
                    openapi_client.models.adresa_vr.AdresaVr()
                    ],
                pravni_forma = [
                    openapi_client.models.pravni_forma_vr.PravniFormaVr()
                    ],
                obchodni_jmeno = [
                    openapi_client.models.obchodni_jmeno_vr.ObchodniJmenoVr()
                    ]
            )
        else:
            return OdstepnyZavodVr(
        )
        """

    def testOdstepnyZavodVr(self):
        """Test OdstepnyZavodVr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
