# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.spolecnici_vr import SpolecniciVr

class TestSpolecniciVr(unittest.TestCase):
    """SpolecniciVr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpolecniciVr:
        """Test SpolecniciVr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpolecniciVr`
        """
        model = SpolecniciVr()
        if include_optional:
            return SpolecniciVr(
                datum_zapisu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_vymazu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                nazev_organu = '',
                spolecnik = [
                    openapi_client.models.spolecnik_vr.SpolecnikVr()
                    ],
                spolecny_podil = [
                    openapi_client.models.spolecny_podil_vr.SpolecnyPodilVr()
                    ],
                typ_organu = '0',
                uvolneny_podil = [
                    openapi_client.models.uvolneny_podil_vr.UvolnenyPodilVr()
                    ],
                nazev = ''
            )
        else:
            return SpolecniciVr(
        )
        """

    def testSpolecniciVr(self):
        """Test SpolecniciVr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
