# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ciselniky_nazevniky_api import CiselnikyNazevnikyApi


class TestCiselnikyNazevnikyApi(unittest.TestCase):
    """CiselnikyNazevnikyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CiselnikyNazevnikyApi()

    def tearDown(self) -> None:
        pass

    def test_vyhledej_ciselnik(self) -> None:
        """Test case for vyhledej_ciselnik

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
