# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cinnosti_vr import CinnostiVr

class TestCinnostiVr(unittest.TestCase):
    """CinnostiVr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CinnostiVr:
        """Test CinnostiVr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CinnostiVr`
        """
        model = CinnostiVr()
        if include_optional:
            return CinnostiVr(
                predmet_podnikani = [
                    openapi_client.models.obecny_text_vr.ObecnyTextVr()
                    ],
                doplnkova_cinnost = [
                    openapi_client.models.obecny_text_vr.ObecnyTextVr()
                    ],
                predmet_cinnosti = [
                    openapi_client.models.obecny_text_vr.ObecnyTextVr()
                    ],
                ucel = [
                    openapi_client.models.obecny_text_vr.ObecnyTextVr()
                    ]
            )
        else:
            return CinnostiVr(
        )
        """

    def testCinnostiVr(self):
        """Test CinnostiVr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
