# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ekonomicky_subjekt_rpsh import EkonomickySubjektRpsh

class TestEkonomickySubjektRpsh(unittest.TestCase):
    """EkonomickySubjektRpsh unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EkonomickySubjektRpsh:
        """Test EkonomickySubjektRpsh
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EkonomickySubjektRpsh`
        """
        model = EkonomickySubjektRpsh()
        if include_optional:
            return EkonomickySubjektRpsh(
                ico_id = 'ARES_48072888',
                zaznamy = [
                    openapi_client.models.zaznam_rpsh.ZaznamRpsh()
                    ]
            )
        else:
            return EkonomickySubjektRpsh(
        )
        """

    def testEkonomickySubjektRpsh(self):
        """Test EkonomickySubjektRpsh"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
