# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.adresa_filtr import AdresaFiltr

class TestAdresaFiltr(unittest.TestCase):
    """AdresaFiltr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdresaFiltr:
        """Test AdresaFiltr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdresaFiltr`
        """
        model = AdresaFiltr()
        if include_optional:
            return AdresaFiltr(
                kod_casti_obce = 0,
                kod_spravniho_obvodu = 0,
                kod_mestske_casti_obvodu = 0,
                kod_ulice = 0,
                cislo_domovni = 56,
                kod_obce = 0,
                cislo_orientacni = 56,
                cislo_orientacni_pismeno = '',
                textova_adresa = ''
            )
        else:
            return AdresaFiltr(
        )
        """

    def testAdresaFiltr(self):
        """Test AdresaFiltr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
