# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.zakladni_kapital_vr import ZakladniKapitalVr

class TestZakladniKapitalVr(unittest.TestCase):
    """ZakladniKapitalVr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZakladniKapitalVr:
        """Test ZakladniKapitalVr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZakladniKapitalVr`
        """
        model = ZakladniKapitalVr()
        if include_optional:
            return ZakladniKapitalVr(
                datum_zapisu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_vymazu = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                typ_jmeni = '',
                text = '',
                vklad = openapi_client.models.obnos_vr.ObnosVr(
                    typ_obnos = '', 
                    hodnota = '', ),
                splaceni = openapi_client.models.obnos_vr.ObnosVr(
                    typ_obnos = '', 
                    hodnota = '', )
            )
        else:
            return ZakladniKapitalVr(
        )
        """

    def testZakladniKapitalVr(self):
        """Test ZakladniKapitalVr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
