# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pravnicka_osoba_vr import PravnickaOsobaVr

class TestPravnickaOsobaVr(unittest.TestCase):
    """PravnickaOsobaVr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PravnickaOsobaVr:
        """Test PravnickaOsobaVr
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PravnickaOsobaVr`
        """
        model = PravnickaOsobaVr()
        if include_optional:
            return PravnickaOsobaVr(
                text_osoba = '',
                text_osoba_od = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                adresa = openapi_client.models.adresa.Adresa(
                    kod_statu = '012', 
                    nazev_statu = '', 
                    kod_kraje = 0, 
                    nazev_kraje = '', 
                    kod_okresu = 0, 
                    nazev_okresu = '', 
                    kod_obce = 0, 
                    nazev_obce = '', 
                    kod_spravniho_obvodu = 0, 
                    nazev_spravniho_obvodu = '', 
                    kod_mestskeho_obvodu = 0, 
                    nazev_mestskeho_obvodu = '', 
                    kod_mestske_casti_obvodu = 0, 
                    kod_ulice = 0, 
                    nazev_mestske_casti_obvodu = '', 
                    nazev_ulice = '', 
                    cislo_domovni = 56, 
                    doplnek_adresy = '', 
                    kod_casti_obce = 0, 
                    cislo_orientacni = 56, 
                    cislo_orientacni_pismeno = '', 
                    nazev_casti_obce = '', 
                    kod_adresniho_mista = 0, 
                    psc = 56, 
                    textova_adresa = '', 
                    cislo_do_adresy = '', 
                    typ_cislo_domovni = '0', 
                    standardizace_adresy = True, 
                    psc_txt = '', ),
                text_osoba_do = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                ico = '0480728801234567',
                obchodni_jmeno = '0',
                zastoupeni = [
                    openapi_client.models.angazma_fyzicka_osoba_vr.AngazmaFyzickaOsobaVr()
                    ],
                pravni_forma = '048012'
            )
        else:
            return PravnickaOsobaVr(
        )
        """

    def testPravnickaOsobaVr(self):
        """Test PravnickaOsobaVr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
