# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ciselniky_nazevnik_seznam import CiselnikyNazevnikSeznam

class TestCiselnikyNazevnikSeznam(unittest.TestCase):
    """CiselnikyNazevnikSeznam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CiselnikyNazevnikSeznam:
        """Test CiselnikyNazevnikSeznam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CiselnikyNazevnikSeznam`
        """
        model = CiselnikyNazevnikSeznam()
        if include_optional:
            return CiselnikyNazevnikSeznam(
                pocet_celkem = 0,
                ciselniky = [
                    openapi_client.models.ciselnik.Ciselnik(
                        kod_ciselniku = '0', 
                        nazev_ciselniku = '', 
                        polozky_ciselniku = [
                            openapi_client.models.polozka_ciselniku.PolozkaCiselniku(
                                kod = '0', 
                                nazev = [
                                    openapi_client.models.nazev_polozky.NazevPolozky(
                                        kod_jazyka = '', )
                                    ], 
                                platnost_od = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                platnost_do = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                kod_nadrizeny = '0', )
                            ], 
                        zdroj_ciselniku = '0', )
                    ]
            )
        else:
            return CiselnikyNazevnikSeznam(
        )
        """

    def testCiselnikyNazevnikSeznam(self):
        """Test CiselnikyNazevnikSeznam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
