# coding: utf-8

"""
    ARES: REST API - veřejné

    REST rozhraní systému ARES

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ekonomicke_subjekty_rs_api import EkonomickeSubjektyRsApi


class TestEkonomickeSubjektyRsApi(unittest.TestCase):
    """EkonomickeSubjektyRsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EkonomickeSubjektyRsApi()

    def tearDown(self) -> None:
        pass

    def test_vrat_ekonomicky_subjekt_rs(self) -> None:
        """Test case for vrat_ekonomicky_subjekt_rs

        
        """
        pass

    def test_vyhledej_seznam_ekonomickych_subjektu_rs(self) -> None:
        """Test case for vyhledej_seznam_ekonomickych_subjektu_rs

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
