
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-05T15:54:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "18340caf3a5ac94afad70b1a0016c3a8b294124c",
 "version": "1.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
