# coding: utf-8

"""
    Cachet Status Page API

    A java-friendly swagger documentation file based on the documentation for the Cachet Status Page https://cachethq.io/  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cachethq_client
from cachethq_client.api.components_api import ComponentsApi  # noqa: E501
from cachethq_client.rest import ApiException


class TestComponentsApi(unittest.TestCase):
    """ComponentsApi unit test stubs"""

    def setUp(self):
        self.api = ComponentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_component(self):
        """Test case for create_component

        Create a new component.  # noqa: E501
        """
        pass

    def test_delete_component_by_id(self):
        """Test case for delete_component_by_id

        Delete a component.  # noqa: E501
        """
        pass

    def test_get_component_by_id(self):
        """Test case for get_component_by_id

        Get a component.  # noqa: E501
        """
        pass

    def test_get_components(self):
        """Test case for get_components

        Get all components.  # noqa: E501
        """
        pass

    def test_update_component_by_id(self):
        """Test case for update_component_by_id

        Update a component.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
