
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2024-02-07T11:59:32-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0dffe924d2249234063051268659a0705e13ef75",
 "version": "2.4.2.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
