
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-05T16:14:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c70d4717388be68896e1f15368c2442e3128194c",
 "version": "5.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
