
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-05T16:57:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "38b6c68ec4ea8e13625449f5291aea4465ad1189",
 "version": "1.21.0.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
