from os import getenv
import urllib.parse

RABBITMQ_HOST = getenv('RABBITMQ_HOST', 'localhost')
RABBITMQ_PORT = getenv('RABBITMQ_PORT', '5672')
RABBITMQ_EXCHANGE = getenv('RABBITMQ_EXCHANGE', '')
RABBITMQ_QUEUE_EMAIL = getenv('RABBITMQ_QUEUE', 'email')
RABBITMQ_QUEUE_NOTIFICACAO = getenv('RABBITMQ_QUEUE', 'notificacoes')
RABBITMQ_QUEUE_NOTIFICACAO_ADMIN = getenv('RABBITMQ_QUEUE', 'notificacoes_admin')

DEBUG = getenv('DEBUG',True)
PORT = getenv('PORT',9090)

DATABASE_PASSAOWRD = urllib.parse.quote_plus( getenv('DATABASE_PASSAOWRD', "U#aBrpd5873P!@sdRCMQW"))
DATABASE_USER = getenv('DATABASE_USER', 'postgres')
DATABASE_HOST = getenv('DATABASE_HOST', '20.83.136.185')
DATABASE_PORT = getenv('DATABASE_PORT', '5432')
DATABASE_NAME = getenv('DATABASE_NAME', 'carreiras')
SQLALCHEMY_DATABASE_URI = f"postgresql://{DATABASE_USER}:{DATABASE_PASSAOWRD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False