
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-08T09:07:11-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f463d70ef43a90404fb9ce9ed81d4f0233a04702",
 "version": "2.6.70"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
