__title__ = "TNKDEV"
__description__ = "TNKDEV CONTACT"
__version__ = "1.0.5"
__author__ = "K07VN"
__author_email__ = "khanhnekyh2007@gmail.com"
__license__ = "Crypto For Tool - Vietnamese"
__copyright__ = "Copyright K07VN | TNKDEV"
