{# templates/cpu_pkg.tpl #}

<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio FileVersion="4.9"?>
<!--autogenerated {{ timestamp }}-->
<Cpu xmlns="http://br-automation.co.at/AS/Cpu">
  <Objects>
    <Object Type="File" Description="Project specific configuration">Zone.sw</Object>
    <Object Type="File" Description="System configuration" Reference="true">\Physical\_resources\Core.sw</Object>
    <Object Type="File" Description="I/O mapping">IoMap.iom</Object>
    <Object Type="Package" Reference="true">\Physical\_resources\mappServices</Object>
    <Object Type="Package" Reference="true">\Physical\_resources\AccessAndSecurity</Object>
    {% if add_mapp_safety %}
    <Object Type="Package">mappSafety</Object>
    {% endif %}
  </Objects>
  <Configuration ModuleId="X20cCP1584">
    <AutomationRuntime Version="C4.92"/>
    <Build AdditionalBuildOptions="-D _HAS_GIT_VERSION" GccVersion="6.3.0" PreBuildStep="$(AS_PROJECT_PATH)/Scripts/as_build/prebuild.bat $(AS_PROJECT_PATH)"/>
    <DefaultTargetMemory Tasks="UserROM"/>
    <Io Supervision="False"/>
    <Opc WindowsServer="False"/>
    <Safety SafetyRelease="0.0"/>
    <Transfer AddToUserPart="True" AdditionalUserDir="\Scripts\as_build\user_partition" AllowDowngrade="True" AllowInitialTransfer="False" AllowPartitioning="False" ExecuteInitExitProgram="True" ForceInitialTransfer="False" GenerateRUCPackage="True" IdentificationTypeValue="" IgnoreVersion="True" KeepNonVolatileMemory="False" PreserveVariableValues="False" ProjectConsistent="False" RebootDuringTransfer="True" SavedOfflineInstallationFolder="" SavedPipDestinationFolder="" SavedRuntimeUtilityCenterPackagePath="" TargetIdentificationType="Always" TryToBootInRunMode="False" UserFilesIgnoreDifference="False"/>
    <Vc FirmwareVersion=""/>
    <OnlineConfiguration Name="PLC_XX" DeviceType="TCPIP" DeviceParameters="/IF=tcpip /LOPO=00000 /SA=0" ConnectionParameters="/COMT=0000 /RT=0000 /AM=* /SDT=0 /DAIP=0.0.0.0 /REPO=00000 /ANSL=0 /PT=0" Description=""/>
  </Configuration>
</Cpu>
<!--end of autogenerated-->
