
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T14:57:53-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e293a1072eb6b89713a780b9442c55d4d5e4d16",
 "version": "12.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
