gbq_log_schema = {
    "hostname": {
        "data_type": "STRING",
        "precision": 0,
        "scale": 0,
        "length": 0,
        "is_nullable": "YES",
        "col_id": 0,
    },
    "job_uuid": {
        "data_type": "STRING",
        "precision": 0,
        "scale": 0,
        "length": 0,
        "is_nullable": "YES",
        "col_id": 0,
    },
    "dataset_name": {
        "data_type": "STRING",
        "precision": 0,
        "scale": 0,
        "length": 0,
        "is_nullable": "YES",
        "col_id": 0,
    },
    "table_name": {
        "data_type": "STRING",
        "precision": 0,
        "scale": 0,
        "length": 0,
        "is_nullable": "YES",
        "col_id": 0,
    },
    "message": {
        "data_type": "STRING",
        "precision": 0,
        "scale": 0,
        "length": 0,
        "is_nullable": "YES",
        "col_id": 0,
    },
    "is_error": {
        "data_type": "INT64",
        "precision": 0,
        "scale": 0,
        "length": 0,
        "is_nullable": "YES",
        "col_id": 0,
    },
    "create_timestamp": {
        "data_type": "TIMESTAMP",
        "precision": 0,
        "scale": 0,
        "length": 0,
        "is_nullable": "YES",
        "col_id": 0,
    },
}
