# Spec version 1.1.0
# This file is auto-generated by setup.py

from .base_types import AnnotationTypesBase


class AnnotationTypes(AnnotationTypesBase):
    """
    This class contains the CLAMS annotation types 
    defined in the spec version 1.1.0 as class variables. 
    """
    Annotation = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/Annotation/v2')
    Region = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/Region/v1')
    TimePoint = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/TimePoint/v1')
    Interval = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/Interval/v1')
    Span = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/Span/v2')
    TimeFrame = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/TimeFrame/v2')
    Chapter = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/Chapter/v1')
    Polygon = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/Polygon/v1')
    BoundingBox = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/BoundingBox/v1')
    VideoObject = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/VideoObject/v1')
    Relation = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/Relation/v1')
    Alignment = AnnotationTypesBase('http://mmif.clams.ai/vocabulary/Alignment/v1')
    typevers = {'Annotation': 'v2', 'Region': 'v1', 'TimePoint': 'v1', 'Interval': 'v1', 'Span': 'v2', 'TimeFrame': 'v2', 'Chapter': 'v1', 'Polygon': 'v1', 'BoundingBox': 'v1', 'VideoObject': 'v1', 'Relation': 'v1', 'Alignment': 'v1'}
