from .addwidgets_ps import icons_path
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gPairsQxaAJC.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QFrame,
    QHBoxLayout, QLabel, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QScrollArea,
    QSizePolicy, QSpacerItem, QStatusBar, QToolButton,
    QVBoxLayout, QWidget)

from .addwidgets_ps import (MyQSpin, RichTextPushButton, myQSplitter)

class Ui_gPairs(object):
    def setupUi(self, gPairs):
        if not gPairs.objectName():
            gPairs.setObjectName(u"gPairs")
        gPairs.resize(1200, 800)
        gPairs.setMinimumSize(QSize(880, 0))
        font = QFont()
        font.setPointSize(11)
        gPairs.setFont(font)
        icon = QIcon()
        icon.addFile(u""+ icons_path +"icon_PaIRS.png", QSize(), QIcon.Normal, QIcon.Off)
        gPairs.setWindowIcon(icon)
        gPairs.setUnifiedTitleAndToolBarOnMac(False)
        self.actionExit = QAction(gPairs)
        self.actionExit.setObjectName(u"actionExit")
        self.aExit = QAction(gPairs)
        self.aExit.setObjectName(u"aExit")
        icon1 = QIcon()
        icon1.addFile(u""+ icons_path +"quit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.aExit.setIcon(icon1)
        self.aExit.setShortcutVisibleInContextMenu(True)
        self.actionSave = QAction(gPairs)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile(u""+ icons_path +"save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setShortcutVisibleInContextMenu(True)
        self.actionLoad = QAction(gPairs)
        self.actionLoad.setObjectName(u"actionLoad")
        icon3 = QIcon()
        icon3.addFile(u""+ icons_path +"open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLoad.setIcon(icon3)
        self.actionLoad.setShortcutVisibleInContextMenu(True)
        self.actionNew = QAction(gPairs)
        self.actionNew.setObjectName(u"actionNew")
        icon4 = QIcon()
        icon4.addFile(u""+ icons_path +"new.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon4)
        self.actionNew.setShortcutVisibleInContextMenu(True)
        self.actionAbout = QAction(gPairs)
        self.actionAbout.setObjectName(u"actionAbout")
        icon5 = QIcon()
        icon5.addFile(u""+ icons_path +"about.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setShortcutVisibleInContextMenu(True)
        self.actionGuide = QAction(gPairs)
        self.actionGuide.setObjectName(u"actionGuide")
        icon6 = QIcon()
        icon6.addFile(u""+ icons_path +"guide.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionGuide.setIcon(icon6)
        self.actionSave_as = QAction(gPairs)
        self.actionSave_as.setObjectName(u"actionSave_as")
        icon7 = QIcon()
        icon7.addFile(u""+ icons_path +"saveas.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_as.setIcon(icon7)
        self.actionSave_as.setShortcutVisibleInContextMenu(True)
        self.actionClose = QAction(gPairs)
        self.actionClose.setObjectName(u"actionClose")
        icon8 = QIcon()
        icon8.addFile(u""+ icons_path +"close_project.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon8)
        self.actionClose.setShortcutVisibleInContextMenu(True)
        self.actionPaIRS_Run = QAction(gPairs)
        self.actionPaIRS_Run.setObjectName(u"actionPaIRS_Run")
        icon9 = QIcon()
        icon9.addFile(u""+ icons_path +"normal_run.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaIRS_Run.setIcon(icon9)
        self.actionPaIRS_Clean_run = QAction(gPairs)
        self.actionPaIRS_Clean_run.setObjectName(u"actionPaIRS_Clean_run")
        icon10 = QIcon()
        icon10.addFile(u""+ icons_path +"clean_run.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaIRS_Clean_run.setIcon(icon10)
        self.actionPaIRS_Debug_run = QAction(gPairs)
        self.actionPaIRS_Debug_run.setObjectName(u"actionPaIRS_Debug_run")
        icon11 = QIcon()
        icon11.addFile(u""+ icons_path +"debug_run.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaIRS_Debug_run.setIcon(icon11)
        self.actionCalVi_Run = QAction(gPairs)
        self.actionCalVi_Run.setObjectName(u"actionCalVi_Run")
        self.actionCalVi_Run.setIcon(icon9)
        self.actionCalVi_Clean_run = QAction(gPairs)
        self.actionCalVi_Clean_run.setObjectName(u"actionCalVi_Clean_run")
        self.actionCalVi_Clean_run.setIcon(icon10)
        self.actionCalVi_Debug_run = QAction(gPairs)
        self.actionCalVi_Debug_run.setObjectName(u"actionCalVi_Debug_run")
        self.actionCalVi_Debug_run.setIcon(icon11)
        self.actionChanges = QAction(gPairs)
        self.actionChanges.setObjectName(u"actionChanges")
        icon12 = QIcon()
        icon12.addFile(u""+ icons_path +"news.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionChanges.setIcon(icon12)
        self.centralwidget = QWidget(gPairs)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(880, 0))
        self.Clayout = QHBoxLayout(self.centralwidget)
        self.Clayout.setSpacing(0)
        self.Clayout.setObjectName(u"Clayout")
        self.Clayout.setContentsMargins(10, 0, 10, 0)
        self.main_splitter = myQSplitter(self.centralwidget)
        self.main_splitter.setObjectName(u"main_splitter")
        self.main_splitter.setOrientation(Qt.Horizontal)
        self.main_splitter.setOpaqueResize(False)
        self.main_splitter.setHandleWidth(10)
        self.main_splitter.setChildrenCollapsible(False)
        self.w_Managing_Tabs = QWidget(self.main_splitter)
        self.w_Managing_Tabs.setObjectName(u"w_Managing_Tabs")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_Managing_Tabs.sizePolicy().hasHeightForWidth())
        self.w_Managing_Tabs.setSizePolicy(sizePolicy)
        self.w_Managing_Tabs.setMinimumSize(QSize(320, 0))
        self.w_Managing_Tabs.setMaximumSize(QSize(810, 16777215))
        self.manlay = QVBoxLayout(self.w_Managing_Tabs)
        self.manlay.setSpacing(5)
        self.manlay.setObjectName(u"manlay")
        self.manlay.setContentsMargins(0, 0, 0, 0)
        self.w_logo_run = QWidget(self.w_Managing_Tabs)
        self.w_logo_run.setObjectName(u"w_logo_run")
        self.w_logo_run.setMinimumSize(QSize(0, 80))
        self.w_logo_run.setMaximumSize(QSize(16777215, 80))
        self.verticalLayout = QVBoxLayout(self.w_logo_run)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.w_Buttons_Run = QWidget(self.w_logo_run)
        self.w_Buttons_Run.setObjectName(u"w_Buttons_Run")
        self.w_Buttons_Run.setMinimumSize(QSize(0, 60))
        self.w_Buttons_Run.setMaximumSize(QSize(16777215, 60))
        self.horizontalLayout_10 = QHBoxLayout(self.w_Buttons_Run)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.logo = QLabel(self.w_Buttons_Run)
        self.logo.setObjectName(u"logo")
        self.logo.setMinimumSize(QSize(92, 60))
        self.logo.setMaximumSize(QSize(92, 60))
        self.logo.setPixmap(QPixmap(u""+ icons_path +"logo_PaIRS_rect.png"))
        self.logo.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.logo)

        self.button_PaIRS_download = QToolButton(self.w_Buttons_Run)
        self.button_PaIRS_download.setObjectName(u"button_PaIRS_download")
        self.button_PaIRS_download.setMinimumSize(QSize(30, 30))
        self.button_PaIRS_download.setMaximumSize(QSize(30, 30))
        font1 = QFont()
        font1.setPointSize(16)
        self.button_PaIRS_download.setFont(font1)
        self.button_PaIRS_download.setStyleSheet(u"border: none")
        icon13 = QIcon()
        icon13.addFile(u""+ icons_path +"flaticon_PaIRS_download.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_PaIRS_download.setIcon(icon13)
        self.button_PaIRS_download.setIconSize(QSize(24, 24))
        self.button_PaIRS_download.setCheckable(False)

        self.horizontalLayout_10.addWidget(self.button_PaIRS_download)

        self.hs_logo = QSpacerItem(200, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_10.addItem(self.hs_logo)

        self.label_updating_import = QLabel(self.w_Buttons_Run)
        self.label_updating_import.setObjectName(u"label_updating_import")
        self.label_updating_import.setMinimumSize(QSize(40, 40))
        self.label_updating_import.setMaximumSize(QSize(40, 40))

        self.horizontalLayout_10.addWidget(self.label_updating_import)

        self.label_updating_pairs = QLabel(self.w_Buttons_Run)
        self.label_updating_pairs.setObjectName(u"label_updating_pairs")
        self.label_updating_pairs.setMinimumSize(QSize(40, 40))
        self.label_updating_pairs.setMaximumSize(QSize(40, 40))

        self.horizontalLayout_10.addWidget(self.label_updating_pairs)

        self.w_progress_Proc = QWidget(self.w_Buttons_Run)
        self.w_progress_Proc.setObjectName(u"w_progress_Proc")
        self.w_progress_Proc.setMinimumSize(QSize(0, 60))
        self.w_progress_Proc.setMaximumSize(QSize(16777215, 60))
        font2 = QFont()
        font2.setPointSize(13)
        self.w_progress_Proc.setFont(font2)
        self.verticalLayout_2 = QVBoxLayout(self.w_progress_Proc)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.w_progress = QWidget(self.w_progress_Proc)
        self.w_progress.setObjectName(u"w_progress")
        self.horizontalLayout = QHBoxLayout(self.w_progress)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.progress_Proc = QProgressBar(self.w_progress)
        self.progress_Proc.setObjectName(u"progress_Proc")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.progress_Proc.sizePolicy().hasHeightForWidth())
        self.progress_Proc.setSizePolicy(sizePolicy1)
        self.progress_Proc.setMinimumSize(QSize(100, 36))
        self.progress_Proc.setMaximumSize(QSize(300, 36))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setKerning(True)
        self.progress_Proc.setFont(font3)
        self.progress_Proc.setStyleSheet(u"")
        self.progress_Proc.setValue(24)
        self.progress_Proc.setAlignment(Qt.AlignCenter)
        self.progress_Proc.setInvertedAppearance(False)

        self.horizontalLayout.addWidget(self.progress_Proc)

        self.button_pause = QToolButton(self.w_progress)
        self.button_pause.setObjectName(u"button_pause")
        sizePolicy.setHeightForWidth(self.button_pause.sizePolicy().hasHeightForWidth())
        self.button_pause.setSizePolicy(sizePolicy)
        self.button_pause.setMinimumSize(QSize(36, 36))
        self.button_pause.setMaximumSize(QSize(36, 36))
        self.button_pause.setFont(font1)
        self.button_pause.setToolTipDuration(-1)
        self.button_pause.setLayoutDirection(Qt.LeftToRight)
        icon14 = QIcon()
        icon14.addFile(u""+ icons_path +"pause.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_pause.setIcon(icon14)
        self.button_pause.setIconSize(QSize(28, 28))
        self.button_pause.setPopupMode(QToolButton.DelayedPopup)
        self.button_pause.setToolButtonStyle(Qt.ToolButtonIconOnly)

        self.horizontalLayout.addWidget(self.button_pause)


        self.verticalLayout_2.addWidget(self.w_progress)

        self.time_stamp = QLabel(self.w_progress_Proc)
        self.time_stamp.setObjectName(u"time_stamp")
        self.time_stamp.setMinimumSize(QSize(0, 22))
        self.time_stamp.setMaximumSize(QSize(16777215, 22))
        self.time_stamp.setFont(font)

        self.verticalLayout_2.addWidget(self.time_stamp)


        self.horizontalLayout_10.addWidget(self.w_progress_Proc)

        self.button_Run = QPushButton(self.w_Buttons_Run)
        self.button_Run.setObjectName(u"button_Run")
        sizePolicy.setHeightForWidth(self.button_Run.sizePolicy().hasHeightForWidth())
        self.button_Run.setSizePolicy(sizePolicy)
        self.button_Run.setMinimumSize(QSize(0, 40))
        self.button_Run.setMaximumSize(QSize(16777215, 40))
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(15)
        self.button_Run.setFont(font4)

        self.horizontalLayout_10.addWidget(self.button_Run)

        self.horizontalLayout_10.setStretch(2, 1)

        self.verticalLayout.addWidget(self.w_Buttons_Run)

        self.lab_happy_days = QLabel(self.w_logo_run)
        self.lab_happy_days.setObjectName(u"lab_happy_days")
        self.lab_happy_days.setMinimumSize(QSize(0, 20))
        self.lab_happy_days.setMaximumSize(QSize(16777215, 20))
        font5 = QFont()
        font5.setPointSize(11)
        font5.setItalic(False)
        font5.setUnderline(False)
        self.lab_happy_days.setFont(font5)

        self.verticalLayout.addWidget(self.lab_happy_days)


        self.manlay.addWidget(self.w_logo_run)

        self.f_Tree_Process = QFrame(self.w_Managing_Tabs)
        self.f_Tree_Process.setObjectName(u"f_Tree_Process")
        sizePolicy.setHeightForWidth(self.f_Tree_Process.sizePolicy().hasHeightForWidth())
        self.f_Tree_Process.setSizePolicy(sizePolicy)
        self.f_Tree_Process.setMinimumSize(QSize(280, 0))
        self.f_Tree_Process.setMaximumSize(QSize(800, 16777215))
        self.f_Tree_Process.setStyleSheet(u"QFrame#f_Tree_Process{\n"
"border: 1px solid gray;\n"
"border-radius: 15px;\n"
"}")
        self.fTree_lay = QVBoxLayout(self.f_Tree_Process)
        self.fTree_lay.setSpacing(0)
        self.fTree_lay.setObjectName(u"fTree_lay")
        self.fTree_lay.setContentsMargins(0, 0, 0, 0)

        self.manlay.addWidget(self.f_Tree_Process)

        self.w_gif_loading = QWidget(self.w_Managing_Tabs)
        self.w_gif_loading.setObjectName(u"w_gif_loading")
        self.w_gif_loading.setMinimumSize(QSize(0, 20))
        self.w_gif_loading.setMaximumSize(QSize(16777215, 20))
        self.horizontalLayout_4 = QHBoxLayout(self.w_gif_loading)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_gif = QLabel(self.w_gif_loading)
        self.label_gif.setObjectName(u"label_gif")
        self.label_gif.setMinimumSize(QSize(40, 10))
        self.label_gif.setMaximumSize(QSize(40, 10))
        font6 = QFont()
        font6.setPointSize(10)
        self.label_gif.setFont(font6)
        self.label_gif.setPixmap(QPixmap(u""+ icons_path +"loaded.png"))

        self.horizontalLayout_4.addWidget(self.label_gif)

        self.label_loading = QLabel(self.w_gif_loading)
        self.label_loading.setObjectName(u"label_loading")
        self.label_loading.setMinimumSize(QSize(0, 20))
        self.label_loading.setMaximumSize(QSize(16777215, 20))
        font7 = QFont()
        font7.setPointSize(11)
        font7.setItalic(True)
        self.label_loading.setFont(font7)

        self.horizontalLayout_4.addWidget(self.label_loading)

        self.spin_nworkers = MyQSpin(self.w_gif_loading)
        self.spin_nworkers.setObjectName(u"spin_nworkers")
        self.spin_nworkers.setMinimumSize(QSize(0, 20))
        self.spin_nworkers.setMaximumSize(QSize(26, 20))
        self.spin_nworkers.setFont(font)
        self.spin_nworkers.setStyleSheet(u"padding-bottom: 2px;")
        self.spin_nworkers.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_nworkers.setProperty("showGroupSeparator", True)

        self.horizontalLayout_4.addWidget(self.spin_nworkers)

        self.label_loading_2 = QLabel(self.w_gif_loading)
        self.label_loading_2.setObjectName(u"label_loading_2")
        sizePolicy1.setHeightForWidth(self.label_loading_2.sizePolicy().hasHeightForWidth())
        self.label_loading_2.setSizePolicy(sizePolicy1)
        self.label_loading_2.setMinimumSize(QSize(0, 20))
        self.label_loading_2.setMaximumSize(QSize(16777215, 20))
        self.label_loading_2.setFont(font7)

        self.horizontalLayout_4.addWidget(self.label_loading_2)


        self.manlay.addWidget(self.w_gif_loading)

        self.main_splitter.addWidget(self.w_Managing_Tabs)
        self.main_sep = QFrame(self.main_splitter)
        self.main_sep.setObjectName(u"main_sep")
        self.main_sep.setFrameShadow(QFrame.Raised)
        self.main_sep.setLineWidth(1)
        self.main_sep.setMidLineWidth(0)
        self.main_sep.setFrameShape(QFrame.VLine)
        self.main_splitter.addWidget(self.main_sep)
        self.w_Operating_Tabs = QWidget(self.main_splitter)
        self.w_Operating_Tabs.setObjectName(u"w_Operating_Tabs")
        sizePolicy.setHeightForWidth(self.w_Operating_Tabs.sizePolicy().hasHeightForWidth())
        self.w_Operating_Tabs.setSizePolicy(sizePolicy)
        self.w_Operating_Tabs.setMinimumSize(QSize(500, 0))
        self.oplay = QVBoxLayout(self.w_Operating_Tabs)
        self.oplay.setSpacing(5)
        self.oplay.setObjectName(u"oplay")
        self.oplay.setContentsMargins(0, 0, 0, 0)
        self.w_Buttons = QWidget(self.w_Operating_Tabs)
        self.w_Buttons.setObjectName(u"w_Buttons")
        self.w_Buttons.setMinimumSize(QSize(460, 80))
        self.w_Buttons.setMaximumSize(QSize(16777215, 80))
        self.horizontalLayout_3 = QHBoxLayout(self.w_Buttons)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.button_default_sizes = QToolButton(self.w_Buttons)
        self.button_default_sizes.setObjectName(u"button_default_sizes")
        self.button_default_sizes.setMinimumSize(QSize(30, 30))
        self.button_default_sizes.setMaximumSize(QSize(30, 30))
        self.button_default_sizes.setFont(font1)
        icon15 = QIcon()
        icon15.addFile(u""+ icons_path +"default_sizes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_default_sizes.setIcon(icon15)
        self.button_default_sizes.setIconSize(QSize(24, 24))
        self.button_default_sizes.setCheckable(False)

        self.horizontalLayout_3.addWidget(self.button_default_sizes)

        self.button_dock = QToolButton(self.w_Buttons)
        self.button_dock.setObjectName(u"button_dock")
        self.button_dock.setMinimumSize(QSize(30, 30))
        self.button_dock.setMaximumSize(QSize(30, 30))
        self.button_dock.setFont(font1)
        icon16 = QIcon()
        icon16.addFile(u""+ icons_path +"undock_tabs.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_dock.setIcon(icon16)
        self.button_dock.setIconSize(QSize(20, 20))
        self.button_dock.setCheckable(False)

        self.horizontalLayout_3.addWidget(self.button_dock)

        self.button_Shape = QToolButton(self.w_Buttons)
        self.button_Shape.setObjectName(u"button_Shape")
        self.button_Shape.setMinimumSize(QSize(30, 30))
        self.button_Shape.setMaximumSize(QSize(30, 30))
        self.button_Shape.setFont(font1)
        self.button_Shape.setStyleSheet(u"")
        icon17 = QIcon()
        icon17.addFile(u""+ icons_path +"chain.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_Shape.setIcon(icon17)
        self.button_Shape.setIconSize(QSize(22, 22))
        self.button_Shape.setCheckable(False)
        self.button_Shape.setArrowType(Qt.NoArrow)

        self.horizontalLayout_3.addWidget(self.button_Shape)

        self.w_button_IOP = QWidget(self.w_Buttons)
        self.w_button_IOP.setObjectName(u"w_button_IOP")
        sizePolicy.setHeightForWidth(self.w_button_IOP.sizePolicy().hasHeightForWidth())
        self.w_button_IOP.setSizePolicy(sizePolicy)
        self.w_button_IOP.setMinimumSize(QSize(200, 40))
        self.w_button_IOP.setMaximumSize(QSize(380, 40))
        self.IOP_butt_lay = QHBoxLayout(self.w_button_IOP)
        self.IOP_butt_lay.setSpacing(0)
        self.IOP_butt_lay.setObjectName(u"IOP_butt_lay")
        self.IOP_butt_lay.setContentsMargins(0, 0, 0, 0)
        self.button_Input = RichTextPushButton(self.w_button_IOP)
        self.button_Input.setObjectName(u"button_Input")
        sizePolicy.setHeightForWidth(self.button_Input.sizePolicy().hasHeightForWidth())
        self.button_Input.setSizePolicy(sizePolicy)
        self.button_Input.setMinimumSize(QSize(50, 40))
        self.button_Input.setMaximumSize(QSize(130, 40))
        font8 = QFont()
        font8.setFamilies([u"Arial"])
        font8.setPointSize(13)
        font8.setBold(False)
        self.button_Input.setFont(font8)
        self.button_Input.setStyleSheet(u"")
        icon18 = QIcon()
        icon18.addFile(u""+ icons_path +"import_logo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_Input.setIcon(icon18)
        self.button_Input.setIconSize(QSize(15, 15))
        self.button_Input.setCheckable(False)

        self.IOP_butt_lay.addWidget(self.button_Input)

        self.link = QLabel(self.w_button_IOP)
        self.link.setObjectName(u"link")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.link.sizePolicy().hasHeightForWidth())
        self.link.setSizePolicy(sizePolicy2)
        self.link.setMinimumSize(QSize(12, 40))
        self.link.setMaximumSize(QSize(12, 40))
        self.link.setPixmap(QPixmap(u""+ icons_path +"ganci.png"))
        self.link.setScaledContents(True)

        self.IOP_butt_lay.addWidget(self.link)

        self.button_Output = RichTextPushButton(self.w_button_IOP)
        self.button_Output.setObjectName(u"button_Output")
        sizePolicy.setHeightForWidth(self.button_Output.sizePolicy().hasHeightForWidth())
        self.button_Output.setSizePolicy(sizePolicy)
        self.button_Output.setMinimumSize(QSize(50, 40))
        self.button_Output.setMaximumSize(QSize(130, 40))
        self.button_Output.setFont(font8)
        self.button_Output.setStyleSheet(u"")
        icon19 = QIcon()
        icon19.addFile(u""+ icons_path +"export_logo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_Output.setIcon(icon19)
        self.button_Output.setIconSize(QSize(15, 15))
        self.button_Output.setCheckable(False)

        self.IOP_butt_lay.addWidget(self.button_Output)

        self.link_2 = QLabel(self.w_button_IOP)
        self.link_2.setObjectName(u"link_2")
        sizePolicy2.setHeightForWidth(self.link_2.sizePolicy().hasHeightForWidth())
        self.link_2.setSizePolicy(sizePolicy2)
        self.link_2.setMinimumSize(QSize(12, 40))
        self.link_2.setMaximumSize(QSize(12, 40))
        self.link_2.setPixmap(QPixmap(u""+ icons_path +"ganci.png"))
        self.link_2.setScaledContents(True)

        self.IOP_butt_lay.addWidget(self.link_2)

        self.button_Process = RichTextPushButton(self.w_button_IOP)
        self.button_Process.setObjectName(u"button_Process")
        sizePolicy.setHeightForWidth(self.button_Process.sizePolicy().hasHeightForWidth())
        self.button_Process.setSizePolicy(sizePolicy)
        self.button_Process.setMinimumSize(QSize(50, 40))
        self.button_Process.setMaximumSize(QSize(130, 40))
        self.button_Process.setFont(font8)
        self.button_Process.setStyleSheet(u"")
        icon20 = QIcon()
        icon20.addFile(u""+ icons_path +"process_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_Process.setIcon(icon20)
        self.button_Process.setIconSize(QSize(15, 15))
        self.button_Process.setCheckable(False)

        self.IOP_butt_lay.addWidget(self.button_Process)


        self.horizontalLayout_3.addWidget(self.w_button_IOP)

        self.hs_buttons = QSpacerItem(20, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.hs_buttons)

        self.w_button_LV = QWidget(self.w_Buttons)
        self.w_button_LV.setObjectName(u"w_button_LV")
        sizePolicy.setHeightForWidth(self.w_button_LV.sizePolicy().hasHeightForWidth())
        self.w_button_LV.setSizePolicy(sizePolicy)
        self.w_button_LV.setMinimumSize(QSize(0, 40))
        self.w_button_LV.setMaximumSize(QSize(270, 40))
        self.horizontalLayout_2 = QHBoxLayout(self.w_button_LV)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.button_Log = RichTextPushButton(self.w_button_LV)
        self.button_Log.setObjectName(u"button_Log")
        sizePolicy.setHeightForWidth(self.button_Log.sizePolicy().hasHeightForWidth())
        self.button_Log.setSizePolicy(sizePolicy)
        self.button_Log.setMinimumSize(QSize(50, 40))
        self.button_Log.setMaximumSize(QSize(130, 40))
        self.button_Log.setFont(font8)
        self.button_Log.setStyleSheet(u"")
        icon21 = QIcon()
        icon21.addFile(u""+ icons_path +"terminal.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_Log.setIcon(icon21)
        self.button_Log.setIconSize(QSize(15, 15))
        self.button_Log.setCheckable(False)

        self.horizontalLayout_2.addWidget(self.button_Log)

        self.button_Vis = RichTextPushButton(self.w_button_LV)
        self.button_Vis.setObjectName(u"button_Vis")
        sizePolicy.setHeightForWidth(self.button_Vis.sizePolicy().hasHeightForWidth())
        self.button_Vis.setSizePolicy(sizePolicy)
        self.button_Vis.setMinimumSize(QSize(50, 40))
        self.button_Vis.setMaximumSize(QSize(130, 40))
        self.button_Vis.setFont(font8)
        self.button_Vis.setStyleSheet(u"")
        icon22 = QIcon()
        icon22.addFile(u""+ icons_path +"vect_field.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_Vis.setIcon(icon22)
        self.button_Vis.setIconSize(QSize(15, 15))
        self.button_Vis.setCheckable(False)

        self.horizontalLayout_2.addWidget(self.button_Vis)


        self.horizontalLayout_3.addWidget(self.w_button_LV)

        self.horizontalLayout_3.setStretch(3, 3)
        self.horizontalLayout_3.setStretch(5, 2)

        self.oplay.addWidget(self.w_Buttons)

        self.scrollArea = QScrollArea(self.w_Operating_Tabs)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setMinimumSize(QSize(0, 0))
        self.scrollArea.setStyleSheet(u" QScrollArea {\n"
"        border: 1pix solid gray;\n"
"    }\n"
"\n"
"QScrollBar:horizontal\n"
"    {\n"
"        height: 15px;\n"
"        margin: 3px 0px 3px 0px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"        background-color:  rgba(200,200,200,50);    /* #2A2929; */\n"
"    }\n"
"\n"
"QScrollBar::handle:horizontal\n"
"    {\n"
"        background-color: rgba(180,180,180,180);      /* #605F5F; */\n"
"        min-width: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"QScrollBar:vertical\n"
"    {\n"
"        background-color: rgba(200,200,200,50);  ;\n"
"        width: 15px;\n"
"        margin: 10px 3px 10px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgba(180,180,180,180);         /* #605F5F; */\n"
"        min-height: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"QScrollBar::add-line {\n"
"        border: none;\n"
"        "
                        "background: none;\n"
"    }\n"
"\n"
"QScrollBar::sub-line {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 4000, 649))
        self.scrollAreaWidgetContents.setMinimumSize(QSize(4000, 0))
        self.flay = QHBoxLayout(self.scrollAreaWidgetContents)
        self.flay.setSpacing(0)
        self.flay.setObjectName(u"flay")
        self.flay.setContentsMargins(0, 0, 0, 0)
        self.secondary_splitter = myQSplitter(self.scrollAreaWidgetContents)
        self.secondary_splitter.setObjectName(u"secondary_splitter")
        self.secondary_splitter.setOrientation(Qt.Horizontal)
        self.secondary_splitter.setOpaqueResize(False)
        self.secondary_splitter.setHandleWidth(10)
        self.secondary_splitter.setChildrenCollapsible(False)
        self.f_ImportTab = QFrame(self.secondary_splitter)
        self.f_ImportTab.setObjectName(u"f_ImportTab")
        self.f_ImportTab.setMinimumSize(QSize(500, 0))
        self.f_ImportTab.setMaximumSize(QSize(750, 16777215))
        self.f_ImportTab.setStyleSheet(u"QFrame#f_ImportTab{\n"
"border: 1px solid gray;\n"
"border-radius: 15px;\n"
"}")
        self.fImport_lay = QHBoxLayout(self.f_ImportTab)
        self.fImport_lay.setObjectName(u"fImport_lay")
        self.fImport_lay.setContentsMargins(0, 0, 0, 0)
        self.secondary_splitter.addWidget(self.f_ImportTab)
        self.f_ExportTab = QFrame(self.secondary_splitter)
        self.f_ExportTab.setObjectName(u"f_ExportTab")
        self.f_ExportTab.setMinimumSize(QSize(500, 0))
        self.f_ExportTab.setMaximumSize(QSize(750, 16777215))
        self.f_ExportTab.setSizeIncrement(QSize(0, 0))
        self.f_ExportTab.setStyleSheet(u"QFrame#f_ExportTab{\n"
"border: 1px solid gray;\n"
"border-radius: 15px;\n"
"}")
        self.f_ExportTab.setFrameShadow(QFrame.Plain)
        self.fExport_lay = QHBoxLayout(self.f_ExportTab)
        self.fExport_lay.setObjectName(u"fExport_lay")
        self.fExport_lay.setContentsMargins(0, 0, 0, 0)
        self.secondary_splitter.addWidget(self.f_ExportTab)
        self.f_ProcessTab = QFrame(self.secondary_splitter)
        self.f_ProcessTab.setObjectName(u"f_ProcessTab")
        self.f_ProcessTab.setMinimumSize(QSize(500, 0))
        self.f_ProcessTab.setMaximumSize(QSize(750, 16777215))
        self.f_ProcessTab.setStyleSheet(u"QFrame#f_ProcessTab{\n"
"border: 1px solid gray;\n"
"border-radius: 15px;\n"
"}")
        self.fProcess_lay = QHBoxLayout(self.f_ProcessTab)
        self.fProcess_lay.setObjectName(u"fProcess_lay")
        self.fProcess_lay.setContentsMargins(0, 0, 0, 0)
        self.secondary_splitter.addWidget(self.f_ProcessTab)
        self.f_LogTab = QFrame(self.secondary_splitter)
        self.f_LogTab.setObjectName(u"f_LogTab")
        self.f_LogTab.setMinimumSize(QSize(500, 0))
        self.f_LogTab.setMaximumSize(QSize(750, 16777215))
        self.f_LogTab.setSizeIncrement(QSize(0, 0))
        self.f_LogTab.setStyleSheet(u"QFrame#f_LogTab{\n"
"border: 1px solid gray;\n"
"border-radius: 15px;\n"
"}")
        self.f_LogTab.setFrameShadow(QFrame.Plain)
        self.fLog_lay = QHBoxLayout(self.f_LogTab)
        self.fLog_lay.setObjectName(u"fLog_lay")
        self.fLog_lay.setContentsMargins(0, 0, 0, 0)
        self.secondary_splitter.addWidget(self.f_LogTab)
        self.f_VisTab = QFrame(self.secondary_splitter)
        self.f_VisTab.setObjectName(u"f_VisTab")
        self.f_VisTab.setMinimumSize(QSize(500, 0))
        self.f_VisTab.setMaximumSize(QSize(750, 16777215))
        self.f_VisTab.setStyleSheet(u"QFrame#f_VisTab{\n"
"border: 1px solid gray;\n"
"border-radius: 15px;\n"
"}")
        self.f_VisTab.setFrameShape(QFrame.Box)
        self.fVis_lay = QHBoxLayout(self.f_VisTab)
        self.fVis_lay.setObjectName(u"fVis_lay")
        self.fVis_lay.setContentsMargins(0, 0, 0, 0)
        self.secondary_splitter.addWidget(self.f_VisTab)
        self.f_empty = QFrame(self.secondary_splitter)
        self.f_empty.setObjectName(u"f_empty")
        sizePolicy.setHeightForWidth(self.f_empty.sizePolicy().hasHeightForWidth())
        self.f_empty.setSizePolicy(sizePolicy)
        self.f_empty.setMinimumSize(QSize(0, 0))
        self.f_empty.setStyleSheet(u"")
        self.secondary_splitter.addWidget(self.f_empty)

        self.flay.addWidget(self.secondary_splitter)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.oplay.addWidget(self.scrollArea)

        self.main_splitter.addWidget(self.w_Operating_Tabs)

        self.Clayout.addWidget(self.main_splitter)

        gPairs.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(gPairs)
        self.statusbar.setObjectName(u"statusbar")
        font9 = QFont()
        font9.setPointSize(11)
        font9.setBold(True)
        font9.setItalic(True)
        self.statusbar.setFont(font9)
        self.statusbar.setStyleSheet(u"color: rgb(0, 0, 255);")
        gPairs.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(gPairs)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1200, 26))
        self.menubar.setFont(font)
        self.menubar.setNativeMenuBar(False)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        icon23 = QIcon()
        icon23.addFile(u""+ icons_path +"flaticon_PaIRS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu.setIcon(icon23)
        self.menuPaIRS = QMenu(self.menu)
        self.menuPaIRS.setObjectName(u"menuPaIRS")
        icon24 = QIcon()
        icon24.addFile(u""+ icons_path +"logo_PaIRS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menuPaIRS.setIcon(icon24)
        self.menuCalVi = QMenu(self.menu)
        self.menuCalVi.setObjectName(u"menuCalVi")
        icon25 = QIcon()
        icon25.addFile(u""+ icons_path +"icon_CalVi.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menuCalVi.setIcon(icon25)
        gPairs.setMenuBar(self.menubar)
        QWidget.setTabOrder(self.spin_nworkers, self.button_default_sizes)
        QWidget.setTabOrder(self.button_default_sizes, self.button_dock)
        QWidget.setTabOrder(self.button_dock, self.button_Shape)
        QWidget.setTabOrder(self.button_Shape, self.scrollArea)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.aExit)
        self.menuHelp.addAction(self.actionChanges)
        self.menuHelp.addAction(self.actionGuide)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menu.addAction(self.menuPaIRS.menuAction())
        self.menu.addAction(self.menuCalVi.menuAction())
        self.menuPaIRS.addAction(self.actionPaIRS_Run)
        self.menuPaIRS.addAction(self.actionPaIRS_Clean_run)
        self.menuPaIRS.addAction(self.actionPaIRS_Debug_run)
        self.menuCalVi.addAction(self.actionCalVi_Run)
        self.menuCalVi.addAction(self.actionCalVi_Clean_run)
        self.menuCalVi.addAction(self.actionCalVi_Debug_run)

        self.retranslateUi(gPairs)

        QMetaObject.connectSlotsByName(gPairs)
    # setupUi

    def retranslateUi(self, gPairs):
        gPairs.setWindowTitle(QCoreApplication.translate("gPairs", u"PaIRS", None))
        self.actionExit.setText(QCoreApplication.translate("gPairs", u"Exit", None))
        self.aExit.setText(QCoreApplication.translate("gPairs", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.aExit.setShortcut(QCoreApplication.translate("gPairs", u"Alt+F4", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("gPairs", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoad.setText(QCoreApplication.translate("gPairs", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionLoad.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew.setText(QCoreApplication.translate("gPairs", u"New", None))
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("gPairs", u"About PaIRS", None))
#if QT_CONFIG(shortcut)
        self.actionAbout.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuide.setText(QCoreApplication.translate("gPairs", u"Guide", None))
#if QT_CONFIG(shortcut)
        self.actionGuide.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_as.setText(QCoreApplication.translate("gPairs", u"Save as...", None))
#if QT_CONFIG(shortcut)
        self.actionSave_as.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose.setText(QCoreApplication.translate("gPairs", u"Close", None))
#if QT_CONFIG(shortcut)
        self.actionClose.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+Esc", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaIRS_Run.setText(QCoreApplication.translate("gPairs", u"Normal run", None))
        self.actionPaIRS_Clean_run.setText(QCoreApplication.translate("gPairs", u"Clean run", None))
        self.actionPaIRS_Debug_run.setText(QCoreApplication.translate("gPairs", u"Debug run", None))
        self.actionCalVi_Run.setText(QCoreApplication.translate("gPairs", u"Normal run", None))
        self.actionCalVi_Clean_run.setText(QCoreApplication.translate("gPairs", u"Clean run", None))
        self.actionCalVi_Debug_run.setText(QCoreApplication.translate("gPairs", u"Debug run", None))
        self.actionChanges.setText(QCoreApplication.translate("gPairs", u"Changes", None))
        self.logo.setText("")
#if QT_CONFIG(tooltip)
        self.button_PaIRS_download.setToolTip(QCoreApplication.translate("gPairs", u"Download the latest version of PaIRS-UniNa", None))
#endif // QT_CONFIG(tooltip)
        self.button_PaIRS_download.setText("")
        self.label_updating_import.setText("")
        self.label_updating_pairs.setText("")
#if QT_CONFIG(tooltip)
        self.button_pause.setToolTip(QCoreApplication.translate("gPairs", u"Pause/restart process queue", None))
#endif // QT_CONFIG(tooltip)
        self.button_pause.setText("")
#if QT_CONFIG(shortcut)
        self.button_pause.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+Return", None))
#endif // QT_CONFIG(shortcut)
        self.time_stamp.setText(QCoreApplication.translate("gPairs", u"Time", None))
#if QT_CONFIG(tooltip)
        self.button_Run.setToolTip(QCoreApplication.translate("gPairs", u"Run and enjoy!", None))
#endif // QT_CONFIG(tooltip)
        self.button_Run.setText(QCoreApplication.translate("gPairs", u"Run", None))
#if QT_CONFIG(shortcut)
        self.button_Run.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+Return", None))
#endif // QT_CONFIG(shortcut)
        self.lab_happy_days.setText(QCoreApplication.translate("gPairs", u"Happy Birthday!", None))
#if QT_CONFIG(tooltip)
        self.f_Tree_Process.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_gif.setText("")
        self.label_loading.setText(QCoreApplication.translate("gPairs", u"Starting parallel pool with", None))
#if QT_CONFIG(tooltip)
        self.spin_nworkers.setToolTip(QCoreApplication.translate("gPairs", u"Insert the number of processors to use in the parallel pool. Press return to set the number", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.spin_nworkers.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.label_loading_2.setText(QCoreApplication.translate("gPairs", u"workers...", None))
#if QT_CONFIG(tooltip)
        self.button_default_sizes.setToolTip(QCoreApplication.translate("gPairs", u"Change sizes", None))
#endif // QT_CONFIG(tooltip)
        self.button_default_sizes.setText("")
#if QT_CONFIG(shortcut)
        self.button_default_sizes.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+Space", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.button_dock.setToolTip(QCoreApplication.translate("gPairs", u"Dock/undock tabs", None))
#endif // QT_CONFIG(tooltip)
        self.button_dock.setText("")
#if QT_CONFIG(shortcut)
        self.button_dock.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.button_Shape.setToolTip(QCoreApplication.translate("gPairs", u"Join/separate Input, Output and Process tabs", None))
#endif // QT_CONFIG(tooltip)
        self.button_Shape.setText("")
#if QT_CONFIG(shortcut)
        self.button_Shape.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.button_Input.setToolTip(QCoreApplication.translate("gPairs", u"Input tab", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.button_Input.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_Input.setText(QCoreApplication.translate("gPairs", u"Input", None))
#if QT_CONFIG(shortcut)
        self.button_Input.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.link.setText("")
#if QT_CONFIG(tooltip)
        self.button_Output.setToolTip(QCoreApplication.translate("gPairs", u"Output tab", None))
#endif // QT_CONFIG(tooltip)
        self.button_Output.setText(QCoreApplication.translate("gPairs", u"Output", None))
#if QT_CONFIG(shortcut)
        self.button_Output.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.link_2.setText("")
#if QT_CONFIG(tooltip)
        self.button_Process.setToolTip(QCoreApplication.translate("gPairs", u"Process tab", None))
#endif // QT_CONFIG(tooltip)
        self.button_Process.setText(QCoreApplication.translate("gPairs", u"Process", None))
#if QT_CONFIG(shortcut)
        self.button_Process.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.button_Log.setToolTip(QCoreApplication.translate("gPairs", u"Log tab", None))
#endif // QT_CONFIG(tooltip)
        self.button_Log.setText(QCoreApplication.translate("gPairs", u"Log", None))
#if QT_CONFIG(shortcut)
        self.button_Log.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.button_Vis.setToolTip(QCoreApplication.translate("gPairs", u"Vis tab", None))
#endif // QT_CONFIG(tooltip)
        self.button_Vis.setText(QCoreApplication.translate("gPairs", u"Vis", None))
#if QT_CONFIG(shortcut)
        self.button_Vis.setShortcut(QCoreApplication.translate("gPairs", u"Ctrl+K", None))
#endif // QT_CONFIG(shortcut)
        self.menuFile.setTitle(QCoreApplication.translate("gPairs", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("gPairs", u"?", None))
        self.menu.setTitle("")
        self.menuPaIRS.setTitle(QCoreApplication.translate("gPairs", u"PaIRS", None))
        self.menuCalVi.setTitle(QCoreApplication.translate("gPairs", u"CalVi", None))
    # retranslateUi

