
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-06T09:54:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6679d3cba959787e253d4667d61e81628c557a55",
 "version": "1.14.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
